#
#	yggr_test_only definitions.
#

LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

# subdirs
subdirs := \
	$(LOCAL_PATH)/../test/Android_algorithm_boyer_moore_horspool_test.mk \
	$(LOCAL_PATH)/../test/Android_algorithm_boyer_moore_test.mk \
	$(LOCAL_PATH)/../test/Android_algorithm_is_permutation_test.mk \
	$(LOCAL_PATH)/../test/Android_algorithm_knuth_morris_pratt_test.mk \
	$(LOCAL_PATH)/../test/Android_algorithm_lexicographical_c_compare_test.mk \
	$(LOCAL_PATH)/../test/Android_algorithm_random_shuffle_test.mk \
	$(LOCAL_PATH)/../test/Android_any_val_any_network_serialize_test.mk \
	$(LOCAL_PATH)/../test/Android_any_val_any_operator_mgr_basic_type_mix_test.mk \
	$(LOCAL_PATH)/../test/Android_any_val_any_operator_mgr_performance_test.mk \
	$(LOCAL_PATH)/../test/Android_any_val_any_xml_serialize_test.mk \
	$(LOCAL_PATH)/../test/Android_any_val_boost_any_operator_mgr_basic_type_test.mk \
	$(LOCAL_PATH)/../test/Android_any_val_params_network_serialize_test.mk \
	$(LOCAL_PATH)/../test/Android_any_val_params_network_serialize_test_utf8_string_key.mk \
	$(LOCAL_PATH)/../test/Android_any_val_params_test_of_boost_any.mk \
	$(LOCAL_PATH)/../test/Android_any_val_params_test_of_yggr_any.mk \
	$(LOCAL_PATH)/../test/Android_any_val_params_xml_serialize_test.mk \
	$(LOCAL_PATH)/../test/Android_any_val_params_xml_serialize_test_utf8_string_key.mk \
	$(LOCAL_PATH)/../test/Android_any_val_yggr_any_operator_mgr_basic_type_test.mk \
	$(LOCAL_PATH)/../test/Android_any_val_yggr_any_test.mk \
	$(LOCAL_PATH)/../test/Android_archive_archive_inner_keys_test.mk \
	$(LOCAL_PATH)/../test/Android_base_char16_32_test.mk \
	$(LOCAL_PATH)/../test/Android_base_cpp_version_test.mk \
	$(LOCAL_PATH)/../test/Android_base_create_object_test.mk \
	$(LOCAL_PATH)/../test/Android_base_random_test.mk \
	$(LOCAL_PATH)/../test/Android_base_test_compare_using_less.mk \
	$(LOCAL_PATH)/../test/Android_base_version_test.mk \
	$(LOCAL_PATH)/../test/Android_bind_ex_bind_comparer_test.mk \
	$(LOCAL_PATH)/../test/Android_bytes_byte_size_test.mk \
	$(LOCAL_PATH)/../test/Android_bytes_tuple_byte_size_test.mk \
	$(LOCAL_PATH)/../test/Android_caller_gen_callable_object_test.mk \
	$(LOCAL_PATH)/../test/Android_caller_to_params_call_test.mk \
	$(LOCAL_PATH)/../test/Android_charset_basic_string_adp_helper_test.mk \
	$(LOCAL_PATH)/../test/Android_charset_charset_base_foo_test.mk \
	$(LOCAL_PATH)/../test/Android_charset_charset_converter_test.mk \
	$(LOCAL_PATH)/../test/Android_charset_const_strings_test.mk \
	$(LOCAL_PATH)/../test/Android_charset_default_charset_name_test.mk \
	$(LOCAL_PATH)/../test/Android_charset_empty_string_string_view_check.mk \
	$(LOCAL_PATH)/../test/Android_charset_escape_codes_converter_test.mk \
	$(LOCAL_PATH)/../test/Android_charset_hex_converter_test.mk \
	$(LOCAL_PATH)/../test/Android_charset_isomeric_same_utf8_string_test.mk \
	$(LOCAL_PATH)/../test/Android_charset_native_string_test.mk \
	$(LOCAL_PATH)/../test/Android_charset_string_byte_size_test.mk \
	$(LOCAL_PATH)/../test/Android_charset_string_converter_test.mk \
	$(LOCAL_PATH)/../test/Android_charset_string_view_test.mk \
	$(LOCAL_PATH)/../test/Android_charset_strings_binary_pak_serialize.mk \
	$(LOCAL_PATH)/../test/Android_charset_strings_network_pak_serialize.mk \
	$(LOCAL_PATH)/../test/Android_charset_strings_text_pak_serialize.mk \
	$(LOCAL_PATH)/../test/Android_charset_strings_xml_pak_serialize.mk \
	$(LOCAL_PATH)/../test/Android_charset_utf8_char_arithmetic_test.mk \
	$(LOCAL_PATH)/../test/Android_charset_utf8_char_cast_conflict_test.mk \
	$(LOCAL_PATH)/../test/Android_charset_utf8_char_isomeric_same_test.mk \
	$(LOCAL_PATH)/../test/Android_charset_utf8_char_reference_test.mk \
	$(LOCAL_PATH)/../test/Android_charset_utf8_char_serialization_test.mk \
	$(LOCAL_PATH)/../test/Android_charset_utf8_char_test.mk \
	$(LOCAL_PATH)/../test/Android_charset_utf8_char_view_test.mk \
	$(LOCAL_PATH)/../test/Android_charset_utf8_foos_test.mk \
	$(LOCAL_PATH)/../test/Android_charset_utf8_string_args_test.mk \
	$(LOCAL_PATH)/../test/Android_charset_utf8_string_binary_pak_serialize.mk \
	$(LOCAL_PATH)/../test/Android_charset_utf8_string_boyer_moore_horspool_test.mk \
	$(LOCAL_PATH)/../test/Android_charset_utf8_string_boyer_moore_test.mk \
	$(LOCAL_PATH)/../test/Android_charset_utf8_string_getter.mk \
	$(LOCAL_PATH)/../test/Android_charset_utf8_string_isomeric_same_test.mk \
	$(LOCAL_PATH)/../test/Android_charset_utf8_string_knuth_morris_pratt_test.mk \
	$(LOCAL_PATH)/../test/Android_charset_utf8_string_serialization_test.mk \
	$(LOCAL_PATH)/../test/Android_charset_utf8_string_test2.mk \
	$(LOCAL_PATH)/../test/Android_charset_utf8_string_test.mk \
	$(LOCAL_PATH)/../test/Android_charset_utf8_string_view_test.mk \
	$(LOCAL_PATH)/../test/Android_charset_utf8_string_xml_pak_serialize.mk \
	$(LOCAL_PATH)/../test/Android_compaction_tool_zip_lzma_test.mk \
	$(LOCAL_PATH)/../test/Android_container_cast_to_native_array_reference_test.mk \
	$(LOCAL_PATH)/../test/Android_container_deque_test.mk \
	$(LOCAL_PATH)/../test/Android_container_ex_array_ex_test.mk \
	$(LOCAL_PATH)/../test/Android_container_ex_array_t_maker_test.mk \
	$(LOCAL_PATH)/../test/Android_container_ex_is_allocator_test.mk \
	$(LOCAL_PATH)/../test/Android_container_ex_is_container_test.mk \
	$(LOCAL_PATH)/../test/Android_container_ex_native_array_ref_test.mk \
	$(LOCAL_PATH)/../test/Android_container_isomeric_same_deque_test.mk \
	$(LOCAL_PATH)/../test/Android_container_isomeric_same_list_test.mk \
	$(LOCAL_PATH)/../test/Android_container_isomeric_same_map_test.mk \
	$(LOCAL_PATH)/../test/Android_container_isomeric_same_multimap_test.mk \
	$(LOCAL_PATH)/../test/Android_container_isomeric_same_multiset_test.mk \
	$(LOCAL_PATH)/../test/Android_container_isomeric_same_options_deque_test.mk \
	$(LOCAL_PATH)/../test/Android_container_isomeric_same_options_map_test.mk \
	$(LOCAL_PATH)/../test/Android_container_isomeric_same_options_multimap_test.mk \
	$(LOCAL_PATH)/../test/Android_container_isomeric_same_options_multiset_test.mk \
	$(LOCAL_PATH)/../test/Android_container_isomeric_same_options_set_test.mk \
	$(LOCAL_PATH)/../test/Android_container_isomeric_same_options_vector_test.mk \
	$(LOCAL_PATH)/../test/Android_container_isomeric_same_set_test.mk \
	$(LOCAL_PATH)/../test/Android_container_isomeric_same_vector_test.mk \
	$(LOCAL_PATH)/../test/Android_container_list_test.mk \
	$(LOCAL_PATH)/../test/Android_container_map_node_handler_test.mk \
	$(LOCAL_PATH)/../test/Android_container_map_test.mk \
	$(LOCAL_PATH)/../test/Android_container_multi_index_node_handler_test.mk \
	$(LOCAL_PATH)/../test/Android_container_multimap_test.mk \
	$(LOCAL_PATH)/../test/Android_container_multiset_test.mk \
	$(LOCAL_PATH)/../test/Android_container_options_deque_test.mk \
	$(LOCAL_PATH)/../test/Android_container_options_map_node_handler_test.mk \
	$(LOCAL_PATH)/../test/Android_container_options_map_test.mk \
	$(LOCAL_PATH)/../test/Android_container_options_multimap_test.mk \
	$(LOCAL_PATH)/../test/Android_container_options_multiset_test.mk \
	$(LOCAL_PATH)/../test/Android_container_options_set_node_handler_test.mk \
	$(LOCAL_PATH)/../test/Android_container_options_set_test.mk \
	$(LOCAL_PATH)/../test/Android_container_options_vector_test.mk \
	$(LOCAL_PATH)/../test/Android_container_queue_test.mk \
	$(LOCAL_PATH)/../test/Android_container_set_node_handler_test.mk \
	$(LOCAL_PATH)/../test/Android_container_set_test.mk \
	$(LOCAL_PATH)/../test/Android_container_stack_test.mk \
	$(LOCAL_PATH)/../test/Android_container_umap_node_handler_test.mk \
	$(LOCAL_PATH)/../test/Android_container_uset_node_handler_test.mk \
	$(LOCAL_PATH)/../test/Android_container_vector_test.mk \
	$(LOCAL_PATH)/../test/Android_database_system_database_accesser_test.mk \
	$(LOCAL_PATH)/../test/Android_database_system_database_accesser_test_of_pool.mk \
	$(LOCAL_PATH)/../test/Android_database_system_database_async_mgr_test.mk \
	$(LOCAL_PATH)/../test/Android_database_system_database_connection_pool_test.mk \
	$(LOCAL_PATH)/../test/Android_database_system_database_connection_pool_test_mt.mk \
	$(LOCAL_PATH)/../test/Android_database_system_database_connection_test.mk \
	$(LOCAL_PATH)/../test/Android_database_system_database_connection_test_mt.mk \
	$(LOCAL_PATH)/../test/Android_database_system_database_mgr_test.mk \
	$(LOCAL_PATH)/../test/Android_database_system_test_database_accesser_excel_extern_file.mk \
	$(LOCAL_PATH)/../test/Android_database_system_test_database_accesser_excel_extern_sheet.mk \
	$(LOCAL_PATH)/../test/Android_database_system_test_database_accesser_excel.mk \
	$(LOCAL_PATH)/../test/Android_encryption_tool_blowfish_tool_test.mk \
	$(LOCAL_PATH)/../test/Android_encryption_tool_hmacsha1_tool_test.mk \
	$(LOCAL_PATH)/../test/Android_encryption_tool_hmacsha256_tool_test.mk \
	$(LOCAL_PATH)/../test/Android_encryption_tool_md5_tool_test.mk \
	$(LOCAL_PATH)/../test/Android_encryption_tool_packet_cypher_tool_test.mk \
	$(LOCAL_PATH)/../test/Android_encryption_tool_safe_pak_tool_test.mk \
	$(LOCAL_PATH)/../test/Android_encryption_tool_sha1_tool_test.mk \
	$(LOCAL_PATH)/../test/Android_encryption_tool_sha256_tool_test.mk \
	$(LOCAL_PATH)/../test/Android_exception_exception_default_log_test.mk \
	$(LOCAL_PATH)/../test/Android_exception_exception_sqldb_log_test.mk \
	$(LOCAL_PATH)/../test/Android_exception_exception_test.mk \
	$(LOCAL_PATH)/../test/Android_exception_exception_thread_file_log_test.mk \
	$(LOCAL_PATH)/../test/Android_exception_link_string.mk \
	$(LOCAL_PATH)/../test/Android_file_system_cross_test_boost_filesystem.mk \
	$(LOCAL_PATH)/../test/Android_file_system_local_fsys_operator_test_part1.mk \
	$(LOCAL_PATH)/../test/Android_file_system_local_fsys_operator_test_part2.mk \
	$(LOCAL_PATH)/../test/Android_file_system_local_fsys_operator_test_part3.mk \
	$(LOCAL_PATH)/../test/Android_file_system_make_path_object_test.mk \
	$(LOCAL_PATH)/../test/Android_file_system_path_check_test_part1.mk \
	$(LOCAL_PATH)/../test/Android_file_system_path_check_test_part2.mk \
	$(LOCAL_PATH)/../test/Android_file_system_path_check_test_part3.mk \
	$(LOCAL_PATH)/../test/Android_func_cast_to_functional_base_test.mk \
	$(LOCAL_PATH)/../test/Android_func_foo_noexcept_op_test.mk \
	$(LOCAL_PATH)/../test/Android_func_foo_t_info_test.mk \
	$(LOCAL_PATH)/../test/Android_func_foo_t_maker_test.mk \
	$(LOCAL_PATH)/../test/Android_func_functional_args_size_test.mk \
	$(LOCAL_PATH)/../test/Android_func_is_functional_test.mk \
	$(LOCAL_PATH)/../test/Android_fuzzy_filter_search_test_part1.mk \
	$(LOCAL_PATH)/../test/Android_fuzzy_filter_search_test_part2.mk \
	$(LOCAL_PATH)/../test/Android_fuzzy_filter_string_test_part1.mk \
	$(LOCAL_PATH)/../test/Android_fuzzy_filter_string_test_part2.mk \
	$(LOCAL_PATH)/../test/Android_fuzzy_fuzzy_search_test_part1.mk \
	$(LOCAL_PATH)/../test/Android_fuzzy_fuzzy_search_test_part2.mk \
	$(LOCAL_PATH)/../test/Android_fuzzy_fuzzy_string_test_part1.mk \
	$(LOCAL_PATH)/../test/Android_fuzzy_fuzzy_string_test_part2.mk \
	$(LOCAL_PATH)/../test/Android_geometry_bresenham_dx_test.mk \
	$(LOCAL_PATH)/../test/Android_geometry_bresenham_test.mk \
	$(LOCAL_PATH)/../test/Android_geometry_geo_bezier_curve_gui_test.mk \
	$(LOCAL_PATH)/../test/Android_geometry_geo_bezier_curve_test.mk \
	$(LOCAL_PATH)/../test/Android_geometry_geo_line_segment_test.mk \
	$(LOCAL_PATH)/../test/Android_geometry_geo_line_test.mk \
	$(LOCAL_PATH)/../test/Android_geometry_geo_polygon_test.mk \
	$(LOCAL_PATH)/../test/Android_geometry_geo_rectangle_test.mk \
	$(LOCAL_PATH)/../test/Android_geometry_org_bresenham_test.mk \
	$(LOCAL_PATH)/../test/Android_handler_center_handler_center_test.mk \
	$(LOCAL_PATH)/../test/Android_handler_center_handler_center_test_performance.mk \
	$(LOCAL_PATH)/../test/Android_handler_center_handler_center_test_same_id_and_out.mk \
	$(LOCAL_PATH)/../test/Android_handler_center_handler_center_test_u32_id.mk \
	$(LOCAL_PATH)/../test/Android_ids_id_generator_test.mk \
	$(LOCAL_PATH)/../test/Android_ids_idn_test.mk \
	$(LOCAL_PATH)/../test/Android_iterator_ex_advance_copy_test.mk \
	$(LOCAL_PATH)/../test/Android_iterator_ex_is_const_iterator_test.mk \
	$(LOCAL_PATH)/../test/Android_iterator_ex_is_reverse_iterator_test.mk \
	$(LOCAL_PATH)/../test/Android_iterator_ex_iterator_category_check_test.mk \
	$(LOCAL_PATH)/../test/Android_iterator_ex_iterator_to_reference_t_test.mk \
	$(LOCAL_PATH)/../test/Android_iterator_ex_iterator_to_value_t_test.mk \
	$(LOCAL_PATH)/../test/Android_iterator_ex_iterator_traits_ex_test.mk \
	$(LOCAL_PATH)/../test/Android_log_log_file_accesser_test.mk \
	$(LOCAL_PATH)/../test/Android_log_log_file_mgr_accesser_test2.mk \
	$(LOCAL_PATH)/../test/Android_log_log_file_mgr_accesser_test.mk \
	$(LOCAL_PATH)/../test/Android_log_log_file_mgr_op_caller_test.mk \
	$(LOCAL_PATH)/../test/Android_log_log_file_mgr_op_test.mk \
	$(LOCAL_PATH)/../test/Android_log_log_file_mgr_test.mk \
	$(LOCAL_PATH)/../test/Android_log_log_file_op_caller_test.mk \
	$(LOCAL_PATH)/../test/Android_log_log_file_op_test.mk \
	$(LOCAL_PATH)/../test/Android_log_log_file_test.mk \
	$(LOCAL_PATH)/../test/Android_log_log_sql_db_accesser_test.mk \
	$(LOCAL_PATH)/../test/Android_log_log_sql_db_op_caller_test.mk \
	$(LOCAL_PATH)/../test/Android_log_log_sql_db_op_test.mk \
	$(LOCAL_PATH)/../test/Android_log_log_thread_file_test.mk \
	$(LOCAL_PATH)/../test/Android_lua_lua_base_type_test_d32.mk \
	$(LOCAL_PATH)/../test/Android_lua_lua_base_type_test_d64.mk \
	$(LOCAL_PATH)/../test/Android_lua_lua_base_type_test_type_info.mk \
	$(LOCAL_PATH)/../test/Android_lua_lua_debug_helper_test.mk \
	$(LOCAL_PATH)/../test/Android_lua_lua_export_any_test.mk \
	$(LOCAL_PATH)/../test/Android_lua_lua_export_inner_process_id.mk \
	$(LOCAL_PATH)/../test/Android_lua_lua_export_pair_test.mk \
	$(LOCAL_PATH)/../test/Android_lua_lua_export_params_test.mk \
	$(LOCAL_PATH)/../test/Android_lua_lua_export_uuid_test.mk \
	$(LOCAL_PATH)/../test/Android_lua_lua_script_mgr_performance_test.mk \
	$(LOCAL_PATH)/../test/Android_lua_lua_script_mgr_test2.mk \
	$(LOCAL_PATH)/../test/Android_lua_lua_script_mgr_test3.mk \
	$(LOCAL_PATH)/../test/Android_lua_lua_script_mgr_test.mk \
	$(LOCAL_PATH)/../test/Android_lua_lua_script_mgr_test_same_id_and_out.mk \
	$(LOCAL_PATH)/../test/Android_lua_lua_script_test.mk \
	$(LOCAL_PATH)/../test/Android_lua_lua_wrap_boost_size_test.mk \
	$(LOCAL_PATH)/../test/Android_lua_luabind_exports_any_link_error_test.mk \
	$(LOCAL_PATH)/../test/Android_lua_wrap_allcator_test.mk \
	$(LOCAL_PATH)/../test/Android_lua_wrap_base_t_test.mk \
	$(LOCAL_PATH)/../test/Android_lua_wrap_bidirectional_iterator_test.mk \
	$(LOCAL_PATH)/../test/Android_lua_wrap_deque_test.mk \
	$(LOCAL_PATH)/../test/Android_lua_wrap_list_test.mk \
	$(LOCAL_PATH)/../test/Android_lua_wrap_pair_test.mk \
	$(LOCAL_PATH)/../test/Android_lua_wrap_random_access_iterator_test_part1.mk \
	$(LOCAL_PATH)/../test/Android_lua_wrap_random_access_iterator_test_part2.mk \
	$(LOCAL_PATH)/../test/Android_lua_wrap_reverse_iterator_test.mk \
	$(LOCAL_PATH)/../test/Android_lua_wrap_vector_test.mk \
	$(LOCAL_PATH)/../test/Android_mapping_static_index_mapping_test.mk \
	$(LOCAL_PATH)/../test/Android_mapping_unique_mapping_test.mk \
	$(LOCAL_PATH)/../test/Android_math_arrangement_test.mk \
	$(LOCAL_PATH)/../test/Android_math_combination_test.mk \
	$(LOCAL_PATH)/../test/Android_math_division_ex_test.mk \
	$(LOCAL_PATH)/../test/Android_math_elo_rating_test.mk \
	$(LOCAL_PATH)/../test/Android_math_factorial_test.mk \
	$(LOCAL_PATH)/../test/Android_math_fast_sqrt_check.mk \
	$(LOCAL_PATH)/../test/Android_math_gcd_lcm_test.mk \
	$(LOCAL_PATH)/../test/Android_math_math_some_test.mk \
	$(LOCAL_PATH)/../test/Android_math_matrix_hash_test.mk \
	$(LOCAL_PATH)/../test/Android_math_matrix_test.mk \
	$(LOCAL_PATH)/../test/Android_math_modulus_test.mk \
	$(LOCAL_PATH)/../test/Android_math_moving_average_test.mk \
	$(LOCAL_PATH)/../test/Android_math_odd_even_number_test.mk \
	$(LOCAL_PATH)/../test/Android_math_odds_test.mk \
	$(LOCAL_PATH)/../test/Android_math_pascals_triangle_test.mk \
	$(LOCAL_PATH)/../test/Android_math_sign_test.mk \
	$(LOCAL_PATH)/../test/Android_math_vector2d_test.mk \
	$(LOCAL_PATH)/../test/Android_math_vector3d_test.mk \
	$(LOCAL_PATH)/../test/Android_math_vector_and_matrix_nvp_seriaztion_test.mk \
	$(LOCAL_PATH)/../test/Android_math_vector_and_matrix_seriaztion_test.mk \
	$(LOCAL_PATH)/../test/Android_math_vector_hash_test.mk \
	$(LOCAL_PATH)/../test/Android_memory_ex_allocator_traits_test.mk \
	$(LOCAL_PATH)/../test/Android_mplex_cast_to_container_test.mk \
	$(LOCAL_PATH)/../test/Android_mplex_conv_to_tuple_test.mk \
	$(LOCAL_PATH)/../test/Android_mplex_get_reference_if_in_test.mk \
	$(LOCAL_PATH)/../test/Android_mplex_interger_log2_test.mk \
	$(LOCAL_PATH)/../test/Android_mplex_limits_test.mk \
	$(LOCAL_PATH)/../test/Android_mplex_pointer_int_test.mk \
	$(LOCAL_PATH)/../test/Android_mplex_pointer_to_reference_t_test.mk \
	$(LOCAL_PATH)/../test/Android_mplex_pointer_to_value_t_test.mk \
	$(LOCAL_PATH)/../test/Android_mplex_ptr_val_operator_test.mk \
	$(LOCAL_PATH)/../test/Android_mplex_reference_to_pointer_t_test.mk \
	$(LOCAL_PATH)/../test/Android_mplex_reference_to_value_t_test.mk \
	$(LOCAL_PATH)/../test/Android_mplex_strict_sizeof_test.mk \
	$(LOCAL_PATH)/../test/Android_mplex_template_repaceor_test.mk \
	$(LOCAL_PATH)/../test/Android_mplex_typename_caster_test.mk \
	$(LOCAL_PATH)/../test/Android_mplex_typename_swapper_test.mk \
	$(LOCAL_PATH)/../test/Android_network_asio_timer_test.mk \
	$(LOCAL_PATH)/../test/Android_network_base_network_packet_test.mk \
	$(LOCAL_PATH)/../test/Android_network_bl_end_test.mk \
	$(LOCAL_PATH)/../test/Android_network_io_service_pool_test.mk \
	$(LOCAL_PATH)/../test/Android_network_network_info_test.mk \
	$(LOCAL_PATH)/../test/Android_network_network_packet_test.mk \
	$(LOCAL_PATH)/../test/Android_packet_binary_archive_test.mk \
	$(LOCAL_PATH)/../test/Android_packet_binary_file_archive_test.mk \
	$(LOCAL_PATH)/../test/Android_packet_binary_pak_archive_test.mk \
	$(LOCAL_PATH)/../test/Android_packet_binary_pak_warchive_test.mk \
	$(LOCAL_PATH)/../test/Android_packet_network_32_64_x_serialization_test.mk \
	$(LOCAL_PATH)/../test/Android_packet_packet_info_key_test.mk \
	$(LOCAL_PATH)/../test/Android_packet_packet_info_test.mk \
	$(LOCAL_PATH)/../test/Android_packet_polymiorphism_serialization.mk \
	$(LOCAL_PATH)/../test/Android_packet_serialize_file_test.mk \
	$(LOCAL_PATH)/../test/Android_packet_shared_ptr_serialization_test.mk \
	$(LOCAL_PATH)/../test/Android_packet_string_serialization_test_eins.mk \
	$(LOCAL_PATH)/../test/Android_packet_string_serialization_test_zwei.mk \
	$(LOCAL_PATH)/../test/Android_packet_test_archive_udp_wrap_and_collecter.mk \
	$(LOCAL_PATH)/../test/Android_packet_test_archive_udp_wrap.mk \
	$(LOCAL_PATH)/../test/Android_packet_test_archive_vector.mk \
	$(LOCAL_PATH)/../test/Android_packet_test_encrypt_archive.mk \
	$(LOCAL_PATH)/../test/Android_packet_test_packet_info_caster.mk \
	$(LOCAL_PATH)/../test/Android_packet_text_archive_test.mk \
	$(LOCAL_PATH)/../test/Android_packet_text_pak_archive_test.mk \
	$(LOCAL_PATH)/../test/Android_packet_text_pak_warchive_test.mk \
	$(LOCAL_PATH)/../test/Android_packet_xml_pak_archive_test.mk \
	$(LOCAL_PATH)/../test/Android_packet_xml_pak_test_of_container_midx.mk \
	$(LOCAL_PATH)/../test/Android_packet_xml_pak_warchive_test.mk \
	$(LOCAL_PATH)/../test/Android_ppex_foo_params_test.mk \
	$(LOCAL_PATH)/../test/Android_ppex_has_member_check_test.mk \
	$(LOCAL_PATH)/../test/Android_ppex_params_expand_test.mk \
	$(LOCAL_PATH)/../test/Android_ppex_string_symbol_test.mk \
	$(LOCAL_PATH)/../test/Android_ppex_va_args_test.mk \
	$(LOCAL_PATH)/../test/Android_proxy_proxy_mode_test.mk \
	$(LOCAL_PATH)/../test/Android_regex_get_string_vector.mk \
	$(LOCAL_PATH)/../test/Android_regex_regex_parse_test_part1.mk \
	$(LOCAL_PATH)/../test/Android_regex_regex_parse_test_part2.mk \
	$(LOCAL_PATH)/../test/Android_regex_regex_parse_test_part3.mk \
	$(LOCAL_PATH)/../test/Android_regex_sting_view_rangex_test.mk \
	$(LOCAL_PATH)/../test/Android_regex_textlow_dir.mk \
	$(LOCAL_PATH)/../test/Android_regex_textlow_fname.mk \
	$(LOCAL_PATH)/../test/Android_regex_textlow.mk \
	$(LOCAL_PATH)/../test/Android_regex_utf8_regex_parse_test_part1.mk \
	$(LOCAL_PATH)/../test/Android_regex_utf8_regex_parse_test_part2.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_boost_container_list_opt_impl_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_boost_container_map_opt_impl_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_boost_container_mmap_opt_impl_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_boost_container_mset_opt_impl_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_boost_container_set_opt_impl_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_boost_multi_index_ha_opt_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_boost_multi_index_hashed_index_ha_opt_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_boost_multi_index_ordered_index_a_opt_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_boost_multi_index_random_access_index_a_opt_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_boost_multi_index_ranked_index_a_opt_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_boost_multi_index_safe_mode_not_thread_safe_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_boost_multi_index_sequenced_index_a_opt_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_boost_size_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_boost_unordered_map_opt_ha_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_boost_unordered_multimap_ha_opt_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_boost_unordered_multiset_ha_opt_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_boost_unordered_set_ha_opt_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_isomeric_same_safe_deque_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_isomeric_same_safe_list_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_isomeric_same_safe_list_test_no_opt.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_isomeric_same_safe_map_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_isomeric_same_safe_map_test_no_opt.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_isomeric_same_safe_multi_index_container_base_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_isomeric_same_safe_multimap_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_isomeric_same_safe_multimap_test_no_opt.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_isomeric_same_safe_multiset_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_isomeric_same_safe_multiset_test_no_opt.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_isomeric_same_safe_options_deque_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_isomeric_same_safe_options_map_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_isomeric_same_safe_options_map_test_no_opt.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_isomeric_same_safe_options_multimap_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_isomeric_same_safe_options_multimap_test_no_opt.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_isomeric_same_safe_options_multiset_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_isomeric_same_safe_options_multiset_test_no_opt.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_isomeric_same_safe_options_set_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_isomeric_same_safe_options_set_test_no_opt.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_isomeric_same_safe_options_vector_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_isomeric_same_safe_set_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_isomeric_same_safe_set_test_no_opt.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_isomeric_same_safe_unordered_map_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_isomeric_same_safe_unordered_multimap_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_isomeric_same_safe_unordered_multiset_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_isomeric_same_safe_unordered_set_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_isomeric_same_safe_vector_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_buffered_object_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_deque_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_hashed_map_queue_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_list_performance_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_list_test_part1_1.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_list_test_part1_2.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_list_test_part1_no_opt.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_list_test_part2.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_list_test_part2_no_opt.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_map_test_part1_1.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_map_test_part1_1_no_opt.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_map_test_part1_2.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_map_test_part1_2_no_opt.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_map_test_part2.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_map_test_part2_no_opt.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_multi_index_container_base_test_part1.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_multi_index_container_base_test_part2.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_multi_index_container_thread_safe_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_multi_index_container_using_handler_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_multi_index_range_and_modify_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_multimap_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_multimap_test_no_opt.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_multiset_performance_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_multiset_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_multiset_test_no_opt.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_options_deque_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_options_map_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_options_map_test_no_opt.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_options_multimap_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_options_multimap_test_no_opt.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_options_multiset_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_options_multiset_test_no_opt.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_options_set_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_options_set_test_no_opt.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_options_vector_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_priority_queue_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_queue_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_set_performance_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_set_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_set_test_no_opt.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_stack_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_stack_test_no_opt.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_unordered_map_opt_performance_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_unordered_map_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_unordered_multimap_opt_performance_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_unordered_multimap_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_unordered_multiset_opt_performance_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_unordered_multiset_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_unordered_set_opt_performance_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_unordered_set_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_vector_test.mk \
	$(LOCAL_PATH)/../test/Android_safe_container_safe_wrap_test.mk \
	$(LOCAL_PATH)/../test/Android_segment_mem_mapped_string_serialization_test.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_container_construct_test2.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_container_construct_test.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_container_test.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_safe_deque_test.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_safe_list_test_part1.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_safe_list_test_part1_no_opt.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_safe_list_test_part2.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_safe_list_test_part2_no_opt.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_safe_list_test_part3.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_safe_list_test_part3_no_opt.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_safe_map_test_part1.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_safe_map_test_part2.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_safe_map_test_part3.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_safe_multi_index_container_base_test_part1.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_safe_multi_index_container_base_test_part2.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_safe_multi_index_container_base_test_part3.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_safe_multi_index_container_base_test_part4.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_safe_multi_index_container_base_test_part5.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_safe_multi_index_container_base_test_part6.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_safe_multimap_test.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_safe_multiset_test.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_safe_options_deque_test.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_safe_options_map_test_part1.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_safe_options_map_test_part2.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_safe_options_map_test_part3.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_safe_options_multimap_test.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_safe_options_multiset_test.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_safe_options_set_test.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_safe_options_vector_test.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_safe_priority_queue_test.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_safe_queue_test.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_safe_set_test.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_safe_set_test_no_opt.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_safe_stack_test_part1.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_safe_stack_test_part2.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_safe_stack_test_part3.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_safe_unordered_map_test_part1.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_safe_unordered_map_test_part2.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_safe_unordered_multimap_test.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_safe_unordered_multiset_test.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_safe_unordered_set_test.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_safe_vector_test.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_utf8_char_test.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_utf8_string_test_part1.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_utf8_string_test_part2.mk \
	$(LOCAL_PATH)/../test/Android_segment_segment_utf8_string_test_part3.mk \
	$(LOCAL_PATH)/../test/Android_seh_seh_bad_alloc_test.mk \
	$(LOCAL_PATH)/../test/Android_seh_seh_stack_overflow_test.mk \
	$(LOCAL_PATH)/../test/Android_seh_seh_test.mk \
	$(LOCAL_PATH)/../test/Android_seh_win_process_foo_test.mk \
	$(LOCAL_PATH)/../test/Android_serialization_polymiorphism_export_test.mk \
	$(LOCAL_PATH)/../test/Android_smart_ptr_ex_eliminate_virtual.mk \
	$(LOCAL_PATH)/../test/Android_smart_ptr_ex_interface_ptr_test.mk \
	$(LOCAL_PATH)/../test/Android_smart_ptr_ex_make_shared_test.mk \
	$(LOCAL_PATH)/../test/Android_struct_conv_params_and_packet_info_conv_test.mk \
	$(LOCAL_PATH)/../test/Android_task_ceneter_network_packet_task_ceneter_test.mk \
	$(LOCAL_PATH)/../test/Android_task_ceneter_task_ceneter_test.mk \
	$(LOCAL_PATH)/../test/Android_time_inner_process_shared_timer_mgr_test.mk \
	$(LOCAL_PATH)/../test/Android_time_runtime_performance_test_test.mk \
	$(LOCAL_PATH)/../test/Android_time_time_basic_foo_test.mk \
	$(LOCAL_PATH)/../test/Android_time_time_serialization_test.mk \
	$(LOCAL_PATH)/../test/Android_time_time_test.mk \
	$(LOCAL_PATH)/../test/Android_time_timer_mgr_seh_test.mk \
	$(LOCAL_PATH)/../test/Android_time_timer_mgr_test.mk \
	$(LOCAL_PATH)/../test/Android_time_timer_test.mk \
	$(LOCAL_PATH)/../test/Android_tuple_tuple_comparer_test.mk \
	$(LOCAL_PATH)/../test/Android_tuple_tuple_test.mk \
	$(LOCAL_PATH)/../test/Android_tuple_yggr_tuple_in_boost_fusion_test.mk \
	$(LOCAL_PATH)/../test/Android_type_traits_bits_bytes_to_types_test.mk \
	$(LOCAL_PATH)/../test/Android_type_traits_has_functional_member_t_test.mk \
	$(LOCAL_PATH)/../test/Android_type_traits_has_operator_function_test.mk \
	$(LOCAL_PATH)/../test/Android_type_traits_has_operator_index_member_access_test.mk \
	$(LOCAL_PATH)/../test/Android_type_traits_has_operator_pointer_member_access_test.mk \
	$(LOCAL_PATH)/../test/Android_type_traits_is_callable_test.mk \
	$(LOCAL_PATH)/../test/Android_type_traits_is_convertiable_size_t_test.mk \
	$(LOCAL_PATH)/../test/Android_type_traits_is_convertiable_test.mk \
	$(LOCAL_PATH)/../test/Android_type_traits_is_same_tpl_test.mk \
	$(LOCAL_PATH)/../test/Android_type_traits_operator_result_test.mk \
	$(LOCAL_PATH)/../test/Android_type_traits_pointer_checker_test.mk \
	$(LOCAL_PATH)/../test/Android_type_traits_reference_checker_test.mk \
	$(LOCAL_PATH)/../test/Android_typeof_deduce_result_test.mk \
	$(LOCAL_PATH)/../test/Android_typeof_default_value_test.mk \
	$(LOCAL_PATH)/../test/Android_utility_args_holder_test.mk \
	$(LOCAL_PATH)/../test/Android_utility_array_get_test.mk \
	$(LOCAL_PATH)/../test/Android_utility_bit_counter_test.mk \
	$(LOCAL_PATH)/../test/Android_utility_copy_or_move_or_swap_test.mk \
	$(LOCAL_PATH)/../test/Android_utility_get_element_test.mk \
	$(LOCAL_PATH)/../test/Android_utility_get_test.mk \
	$(LOCAL_PATH)/../test/Android_utility_member_var_modify_helper_test.mk \
	$(LOCAL_PATH)/../test/Android_utility_pair_compare_test.mk \
	$(LOCAL_PATH)/../test/Android_utility_pair_get_test.mk \
	$(LOCAL_PATH)/../test/Android_utility_sao_buffer_test.mk \
	$(LOCAL_PATH)/../test/Android_utility_typeinfo_hasher_test.mk \


include $(subdirs)
