#!/bin/bash

rm -f ./yggr_lua_base_type.so
ln -s libyggr_lua_base_type.so yggr_lua_base_type.so

chmod a+x *
chmod a-x *.lua

dos2unix begin_test_env_android_termux.sh
dos2unix end_test_env_termux.sh

rm -fr ../test_out

source begin_test_env_android_termux.sh

./algorithm_boyer_moore_horspool_test --batch-test
./algorithm_boyer_moore_test --batch-test
./algorithm_is_permutation_test --batch-test
./algorithm_knuth_morris_pratt_test --batch-test
./algorithm_lexicographical_c_compare_test --batch-test
./algorithm_random_shuffle_test --batch-test
./any_val_any_bson_serialize_test --batch-test
./any_val_any_network_serialize_test --batch-test
./any_val_any_operator_mgr_basic_type_mix_test --batch-test
./any_val_any_operator_mgr_performance_test --batch-test
./any_val_any_xml_serialize_test --batch-test
./any_val_boost_any_operator_mgr_basic_type_test --batch-test
./any_val_params_bson_serialize_test --batch-test
./any_val_params_network_serialize_test --batch-test
./any_val_params_network_serialize_test_utf8_string_key --batch-test
./any_val_params_test_of_boost_any --batch-test
./any_val_params_test_of_yggr_any --batch-test
./any_val_params_xml_serialize_test --batch-test
./any_val_params_xml_serialize_test_utf8_string_key --batch-test
./any_val_yggr_any_operator_mgr_basic_type_test --batch-test
./any_val_yggr_any_test --batch-test
./archive_archive_inner_keys_test --batch-test
./base_char16_32_test --batch-test
./base_cpp_version_test --batch-test
./base_create_object_test --batch-test
./base_random_test --batch-test
./base_test_compare_using_less --batch-test
./base_version_test --batch-test
./bind_ex_bind_comparer_test --batch-test
./bytes_byte_size_test --batch-test
./bytes_tuple_byte_size_test --batch-test
./caller_gen_callable_object_test --batch-test
./caller_to_params_call_test --batch-test
./charset_basic_string_adp_helper_test --batch-test
./charset_charset_base_foo_test --batch-test
./charset_charset_converter_test --batch-test
./charset_const_strings_test --batch-test
./charset_default_charset_name_test --batch-test
./charset_empty_string_string_view_check --batch-test
./charset_escape_codes_converter_test --batch-test
./charset_hex_converter_test --batch-test
./charset_isomeric_same_utf8_string_test --batch-test
./charset_native_string_test --batch-test
./charset_string_byte_size_test --batch-test
./charset_string_converter_test --batch-test
./charset_string_view_test --batch-test
./charset_strings_binary_pak_serialize --batch-test
./charset_strings_network_pak_serialize --batch-test
./charset_strings_text_pak_serialize --batch-test
./charset_strings_xml_pak_serialize --batch-test
./charset_utf8_char_arithmetic_test --batch-test
./charset_utf8_char_cast_conflict_test --batch-test
./charset_utf8_char_isomeric_same_test --batch-test
./charset_utf8_char_reference_test --batch-test
./charset_utf8_char_serialization_test --batch-test
./charset_utf8_char_test --batch-test
./charset_utf8_char_view_test --batch-test
./charset_utf8_foos_test --batch-test
./charset_utf8_string_args_test --batch-test
./charset_utf8_string_binary_pak_serialize --batch-test
./charset_utf8_string_boyer_moore_horspool_test --batch-test
./charset_utf8_string_boyer_moore_test --batch-test
./charset_utf8_string_bson_pak_test --batch-test
./charset_utf8_string_getter --batch-test
./charset_utf8_string_isomeric_same_test --batch-test
./charset_utf8_string_knuth_morris_pratt_test --batch-test
./charset_utf8_string_serialization_test --batch-test
./charset_utf8_string_test2 --batch-test
./charset_utf8_string_test --batch-test
./charset_utf8_string_view_test --batch-test
./charset_utf8_string_xml_pak_serialize --batch-test
./compaction_tool_zip_lzma_test --batch-test
./container_cast_to_native_array_reference_test --batch-test
./container_deque_test --batch-test
./container_ex_array_ex_test --batch-test
./container_ex_array_t_maker_test --batch-test
./container_ex_is_allocator_test --batch-test
./container_ex_is_container_test --batch-test
./container_ex_native_array_ref_test --batch-test
./container_isomeric_same_deque_test --batch-test
./container_isomeric_same_list_test --batch-test
./container_isomeric_same_map_test --batch-test
./container_isomeric_same_multimap_test --batch-test
./container_isomeric_same_multiset_test --batch-test
./container_isomeric_same_options_deque_test --batch-test
./container_isomeric_same_options_map_test --batch-test
./container_isomeric_same_options_multimap_test --batch-test
./container_isomeric_same_options_multiset_test --batch-test
./container_isomeric_same_options_set_test --batch-test
./container_isomeric_same_options_vector_test --batch-test
./container_isomeric_same_set_test --batch-test
./container_isomeric_same_vector_test --batch-test
./container_list_test --batch-test
./container_map_node_handler_test --batch-test
./container_map_test --batch-test
./container_multi_index_node_handler_test --batch-test
./container_multimap_test --batch-test
./container_multiset_test --batch-test
./container_options_deque_test --batch-test
./container_options_map_node_handler_test --batch-test
./container_options_map_test --batch-test
./container_options_multimap_test --batch-test
./container_options_multiset_test --batch-test
./container_options_set_node_handler_test --batch-test
./container_options_set_test --batch-test
./container_options_vector_test --batch-test
./container_queue_test --batch-test
./container_set_node_handler_test --batch-test
./container_set_test --batch-test
./container_stack_test --batch-test
./container_umap_node_handler_test --batch-test
./container_uset_node_handler_test --batch-test
./container_vector_test --batch-test
./encryption_tool_blowfish_tool_test --batch-test
./encryption_tool_hmacsha1_tool_test --batch-test
./encryption_tool_hmacsha256_tool_test --batch-test
./encryption_tool_md5_tool_test --batch-test
./encryption_tool_packet_cypher_tool_test --batch-test
./encryption_tool_safe_pak_tool_test --batch-test
./encryption_tool_sha1_tool_test --batch-test
./encryption_tool_sha256_tool_test --batch-test
./exception_bson_pak_test_of_error_code --batch-test
./exception_exception_default_log_test --batch-test
./exception_exception_mongodb_log_test --batch-test
./exception_exception_sqldb_log_test --batch-test
./exception_exception_test --batch-test
./exception_exception_thread_file_log_test --batch-test
./exception_link_string --batch-test
./file_system_cross_test_boost_filesystem --batch-test
./file_system_local_fsys_operator_test_part1 --batch-test
./file_system_local_fsys_operator_test_part2 --batch-test
./file_system_local_fsys_operator_test_part3 --batch-test
./file_system_make_path_object_test --batch-test
./file_system_path_check_test_part1 --batch-test
./file_system_path_check_test_part2 --batch-test
./file_system_path_check_test_part3 --batch-test
./func_cast_to_functional_base_test --batch-test
./func_foo_noexcept_op_test --batch-test
./func_foo_t_info_test --batch-test
./func_foo_t_maker_test --batch-test
./func_functional_args_size_test --batch-test
./func_is_functional_test --batch-test
./fuzzy_filter_search_test_part1 --batch-test
./fuzzy_filter_search_test_part2 --batch-test
./fuzzy_filter_string_test_part1 --batch-test
./fuzzy_filter_string_test_part2 --batch-test
./fuzzy_fuzzy_search_test_part1 --batch-test
./fuzzy_fuzzy_search_test_part2 --batch-test
./fuzzy_fuzzy_string_test_part1 --batch-test
./fuzzy_fuzzy_string_test_part2 --batch-test
./geometry_bresenham_dx_test --batch-test
./geometry_bresenham_test --batch-test
./geometry_geo_bezier_curve_gui_test --batch-test
./geometry_geo_bezier_curve_test --batch-test
./geometry_geo_line_test --batch-test
./geometry_geo_polygon_test --batch-test
./geometry_geo_rectangle_test --batch-test
./geometry_org_bresenham_test --batch-test
./handler_center_handler_center_test --batch-test
./handler_center_handler_center_test_performance --batch-test
./handler_center_handler_center_test_same_id_and_out --batch-test
./handler_center_handler_center_test_u32_id --batch-test
./ids_id_generator_test --batch-test
./ids_idn_test --batch-test
./ids_uuid_bson_serialize_test --batch-test
./iterator_ex_advance_copy_test --batch-test
./iterator_ex_is_const_iterator_test --batch-test
./iterator_ex_is_reverse_iterator_test --batch-test
./iterator_ex_iterator_category_check_test --batch-test
./iterator_ex_iterator_to_reference_t_test --batch-test
./iterator_ex_iterator_to_value_t_test --batch-test
./iterator_ex_iterator_traits_ex_test --batch-test
./log_log_file_accesser_test --batch-test
./log_log_file_mgr_accesser_test2 --batch-test
./log_log_file_mgr_accesser_test --batch-test
./log_log_file_mgr_op_caller_test --batch-test
./log_log_file_mgr_op_test --batch-test
./log_log_file_mgr_test --batch-test
./log_log_file_op_caller_test --batch-test
./log_log_file_op_test --batch-test
./log_log_file_test --batch-test
./log_log_mongodb_accesser_test --batch-test
./log_log_mongodb_op_caller_test --batch-test
./log_log_mongodb_op_test --batch-test
./log_log_thread_file_test --batch-test
./lua_lua_base_type_test_d32 --batch-test
./lua_lua_base_type_test_d64 --batch-test
./lua_lua_base_type_test_type_info --batch-test
./lua_lua_debug_helper_test --batch-test
./lua_lua_export_any_test --batch-test
./lua_lua_export_inner_process_id --batch-test
./lua_lua_export_pair_test --batch-test
./lua_lua_export_params_test --batch-test
./lua_lua_export_uuid_test --batch-test
./lua_lua_script_mgr_performance_test --batch-test
./lua_lua_script_mgr_test2 --batch-test
./lua_lua_script_mgr_test3 --batch-test
./lua_lua_script_mgr_test --batch-test
./lua_lua_script_mgr_test_same_id_and_out --batch-test
./lua_lua_script_test --batch-test
./lua_lua_wrap_boost_size_test --batch-test
./lua_luabind_exports_any_link_error_test --batch-test
./lua_wrap_allcator_test --batch-test
./lua_wrap_base_t_test --batch-test
./lua_wrap_bidirectional_iterator_test --batch-test
./lua_wrap_deque_test --batch-test
./lua_wrap_list_test --batch-test
./lua_wrap_pair_test --batch-test
./lua_wrap_random_access_iterator_test_part1 --batch-test
./lua_wrap_random_access_iterator_test_part2 --batch-test
./lua_wrap_reverse_iterator_test --batch-test
./lua_wrap_vector_test --batch-test
./mapping_static_index_mapping_test --batch-test
./mapping_unique_mapping_test --batch-test
./math_arrangement_test --batch-test
./math_combination_test --batch-test
./math_division_ex_test --batch-test
./math_elo_rating_test --batch-test
./math_factorial_test --batch-test
./math_fast_sqrt_check --batch-test
./math_gcd_lcm_test --batch-test
./math_math_some_test --batch-test
./math_matrix_hash_test --batch-test
./math_matrix_test --batch-test
./math_modulus_test --batch-test
./math_moving_average_test --batch-test
./math_odd_even_number_test --batch-test
./math_odds_test --batch-test
./math_pascals_triangle_test --batch-test
./math_sign_test --batch-test
./math_vector2d_test --batch-test
./math_vector3d_test --batch-test
./math_vector_and_matrix_nvp_seriaztion_test --batch-test
./math_vector_and_matrix_seriaztion_test --batch-test
./math_vector_hash_test --batch-test
./memory_ex_allocator_traits_test --batch-test
./mplex_cast_to_container_test --batch-test
./mplex_conv_to_tuple_test --batch-test
./mplex_get_reference_if_in_test --batch-test
./mplex_interger_log2_test --batch-test
./mplex_limits_test --batch-test
./mplex_pointer_int_test --batch-test
./mplex_pointer_to_reference_t_test --batch-test
./mplex_pointer_to_value_t_test --batch-test
./mplex_ptr_val_operator_test --batch-test
./mplex_reference_to_pointer_t_test --batch-test
./mplex_reference_to_value_t_test --batch-test
./mplex_strict_sizeof_test --batch-test
./mplex_template_repaceor_test --batch-test
./mplex_typename_caster_test --batch-test
./mplex_typename_swapper_test --batch-test
./network_asio_timer_test --batch-test
./network_base_network_packet_test --batch-test
./network_bl_end_test --batch-test
./network_io_service_pool_test --batch-test
./network_network_info_test --batch-test
./network_network_packet_test --batch-test
./packet_binary_archive_test --batch-test
./packet_binary_file_archive_test --batch-test
./packet_binary_pak_archive_test --batch-test
./packet_binary_pak_warchive_test --batch-test
./packet_bson_cmd_pak_test_of_container_midx --batch-test
./packet_bson_cmd_pak_test_of_container_part1 --batch-test
./packet_bson_cmd_pak_test_of_container_part2 --batch-test
./packet_bson_pak_test_of_class_and_base --batch-test
./packet_bson_pak_test_of_container_part1_1 --batch-test
./packet_bson_pak_test_of_container_part1_2 --batch-test
./packet_bson_pak_test_of_container_part2_1 --batch-test
./packet_bson_pak_test_of_container_part2_2 --batch-test
./packet_bson_pak_test_of_container_part3 --batch-test
./packet_bson_pak_test_of_container_part4 --batch-test
./packet_bson_pak_test_of_tuple_container --batch-test
./packet_bug_test_bson_pak_man --batch-test
./packet_network_32_64_x_serialization_test --batch-test
./packet_packet_info_key_test --batch-test
./packet_packet_info_test --batch-test
./packet_polymiorphism_serialization --batch-test
./packet_serialize_file_test --batch-test
./packet_shared_ptr_bson_serialization_test --batch-test
./packet_shared_ptr_serialization_test --batch-test
./packet_string_serialization_test_eins --batch-test
./packet_string_serialization_test_zwei --batch-test
./packet_test_archive_udp_wrap_and_collecter --batch-test
./packet_test_archive_udp_wrap --batch-test
./packet_test_archive_vector --batch-test
./packet_test_bson_serialization_include --batch-test
./packet_test_encrypt_archive --batch-test
./packet_test_packet_info_caster --batch-test
./packet_text_archive_test --batch-test
./packet_text_pak_archive_test --batch-test
./packet_text_pak_warchive_test --batch-test
./packet_xml_pak_archive_test --batch-test
./packet_xml_pak_test_of_container_midx --batch-test
./packet_xml_pak_warchive_test --batch-test
./ppex_foo_params_test --batch-test
./ppex_has_member_check_test --batch-test
./ppex_params_expand_test --batch-test
./ppex_string_symbol_test --batch-test
./ppex_va_args_test --batch-test
./proxy_proxy_mode_test --batch-test
./regex_get_string_vector --batch-test
./regex_regex_parse_test_part1 --batch-test
./regex_regex_parse_test_part2 --batch-test
./regex_regex_parse_test_part3 --batch-test
./regex_sting_view_rangex_test --batch-test
./regex_textlow_dir --batch-test
./regex_textlow_fname --batch-test
./regex_textlow --batch-test
./regex_utf8_regex_parse_test_part1 --batch-test
./regex_utf8_regex_parse_test_part2 --batch-test
./safe_container_boost_container_list_opt_impl_test --batch-test
./safe_container_boost_container_map_opt_impl_test --batch-test
./safe_container_boost_container_mmap_opt_impl_test --batch-test
./safe_container_boost_container_mset_opt_impl_test --batch-test
./safe_container_boost_container_set_opt_impl_test --batch-test
./safe_container_boost_multi_index_ha_opt_test --batch-test
./safe_container_boost_multi_index_hashed_index_ha_opt_test --batch-test
./safe_container_boost_multi_index_ordered_index_a_opt_test --batch-test
./safe_container_boost_multi_index_random_access_index_a_opt_test --batch-test
./safe_container_boost_multi_index_ranked_index_a_opt_test --batch-test
./safe_container_boost_multi_index_safe_mode_not_thread_safe_test --batch-test
./safe_container_boost_multi_index_sequenced_index_a_opt_test --batch-test
./safe_container_boost_size_test --batch-test
./safe_container_boost_unordered_map_opt_ha_test --batch-test
./safe_container_boost_unordered_multimap_ha_opt_test --batch-test
./safe_container_boost_unordered_multiset_ha_opt_test --batch-test
./safe_container_boost_unordered_set_ha_opt_test --batch-test
./safe_container_isomeric_same_safe_deque_test --batch-test
./safe_container_isomeric_same_safe_list_test --batch-test
./safe_container_isomeric_same_safe_list_test_no_opt --batch-test
./safe_container_isomeric_same_safe_map_test --batch-test
./safe_container_isomeric_same_safe_map_test_no_opt --batch-test
./safe_container_isomeric_same_safe_multi_index_container_base_test --batch-test
./safe_container_isomeric_same_safe_multimap_test --batch-test
./safe_container_isomeric_same_safe_multimap_test_no_opt --batch-test
./safe_container_isomeric_same_safe_multiset_test --batch-test
./safe_container_isomeric_same_safe_multiset_test_no_opt --batch-test
./safe_container_isomeric_same_safe_options_deque_test --batch-test
./safe_container_isomeric_same_safe_options_map_test --batch-test
./safe_container_isomeric_same_safe_options_map_test_no_opt --batch-test
./safe_container_isomeric_same_safe_options_multimap_test --batch-test
./safe_container_isomeric_same_safe_options_multimap_test_no_opt --batch-test
./safe_container_isomeric_same_safe_options_multiset_test --batch-test
./safe_container_isomeric_same_safe_options_multiset_test_no_opt --batch-test
./safe_container_isomeric_same_safe_options_set_test --batch-test
./safe_container_isomeric_same_safe_options_set_test_no_opt --batch-test
./safe_container_isomeric_same_safe_options_vector_test --batch-test
./safe_container_isomeric_same_safe_set_test --batch-test
./safe_container_isomeric_same_safe_set_test_no_opt --batch-test
./safe_container_isomeric_same_safe_unordered_map_test --batch-test
./safe_container_isomeric_same_safe_unordered_multimap_test --batch-test
./safe_container_isomeric_same_safe_unordered_multiset_test --batch-test
./safe_container_isomeric_same_safe_unordered_set_test --batch-test
./safe_container_isomeric_same_safe_vector_test --batch-test
./safe_container_safe_buffered_object_test --batch-test
./safe_container_safe_deque_test --batch-test
./safe_container_safe_hashed_map_queue_test --batch-test
./safe_container_safe_list_performance_test --batch-test
./safe_container_safe_list_test_part1_1 --batch-test
./safe_container_safe_list_test_part1_2 --batch-test
./safe_container_safe_list_test_part1_no_opt --batch-test
./safe_container_safe_list_test_part2 --batch-test
./safe_container_safe_list_test_part2_no_opt --batch-test
./safe_container_safe_map_test_part1_1 --batch-test
./safe_container_safe_map_test_part1_1_no_opt --batch-test
./safe_container_safe_map_test_part1_2 --batch-test
./safe_container_safe_map_test_part1_2_no_opt --batch-test
./safe_container_safe_map_test_part2 --batch-test
./safe_container_safe_map_test_part2_no_opt --batch-test
./safe_container_safe_multi_index_container_base_test_part1 --batch-test
./safe_container_safe_multi_index_container_base_test_part2 --batch-test
./safe_container_safe_multi_index_container_thread_safe_test --batch-test
./safe_container_safe_multi_index_container_using_handler_test --batch-test
./safe_container_safe_multi_index_range_and_modify_test --batch-test
./safe_container_safe_multimap_test --batch-test
./safe_container_safe_multimap_test_no_opt --batch-test
./safe_container_safe_multiset_performance_test --batch-test
./safe_container_safe_multiset_test --batch-test
./safe_container_safe_multiset_test_no_opt --batch-test
./safe_container_safe_options_deque_test --batch-test
./safe_container_safe_options_map_test --batch-test
./safe_container_safe_options_map_test_no_opt --batch-test
./safe_container_safe_options_multimap_test --batch-test
./safe_container_safe_options_multimap_test_no_opt --batch-test
./safe_container_safe_options_multiset_test --batch-test
./safe_container_safe_options_multiset_test_no_opt --batch-test
./safe_container_safe_options_set_test --batch-test
./safe_container_safe_options_set_test_no_opt --batch-test
./safe_container_safe_options_vector_test --batch-test
./safe_container_safe_priority_queue_test --batch-test
./safe_container_safe_queue_test --batch-test
./safe_container_safe_set_performance_test --batch-test
./safe_container_safe_set_test --batch-test
./safe_container_safe_set_test_no_opt --batch-test
./safe_container_safe_stack_test --batch-test
./safe_container_safe_stack_test_no_opt --batch-test
./safe_container_safe_unordered_map_opt_performance_test --batch-test
./safe_container_safe_unordered_map_test --batch-test
./safe_container_safe_unordered_multimap_opt_performance_test --batch-test
./safe_container_safe_unordered_multimap_test --batch-test
./safe_container_safe_unordered_multiset_opt_performance_test --batch-test
./safe_container_safe_unordered_multiset_test --batch-test
./safe_container_safe_unordered_set_opt_performance_test --batch-test
./safe_container_safe_unordered_set_test --batch-test
./safe_container_safe_vector_test --batch-test
./safe_container_safe_wrap_test --batch-test
./seh_seh_bad_alloc_test --batch-test
./seh_seh_stack_overflow_test --batch-test
./seh_seh_test --batch-test
./seh_win_process_foo_test --batch-test
./serialization_polymiorphism_export_test --batch-test
./smart_ptr_ex_eliminate_virtual --batch-test
./smart_ptr_ex_interface_ptr_test --batch-test
./smart_ptr_ex_make_shared_test --batch-test
./struct_conv_params_and_packet_info_conv_test --batch-test
./task_ceneter_network_packet_task_ceneter_test --batch-test
./task_ceneter_task_ceneter_test --batch-test
./time_inner_process_shared_timer_mgr_test --batch-test
./time_runtime_performance_test_test --batch-test
./time_time_basic_foo_test --batch-test
./time_time_serialization_test --batch-test
./time_time_test --batch-test
./time_timer_mgr_seh_test --batch-test
./time_timer_mgr_test --batch-test
./time_timer_test --batch-test
./tuple_tuple_comparer_test --batch-test
./tuple_tuple_test --batch-test
./tuple_yggr_tuple_in_boost_fusion_test --batch-test
./type_traits_bits_bytes_to_types_test --batch-test
./type_traits_has_functional_member_t_test --batch-test
./type_traits_has_operator_function_test --batch-test
./type_traits_has_operator_index_member_access_test --batch-test
./type_traits_has_operator_pointer_member_access_test --batch-test
./type_traits_is_callable_test --batch-test
./type_traits_is_convertiable_size_t_test --batch-test
./type_traits_is_convertiable_test --batch-test
./type_traits_is_same_tpl_test --batch-test
./type_traits_operator_result_test --batch-test
./type_traits_pointer_checker_test --batch-test
./type_traits_reference_checker_test --batch-test
./typeof_deduce_result_test --batch-test
./typeof_default_value_test --batch-test
./utility_args_holder_test --batch-test
./utility_array_get_test --batch-test
./utility_bit_counter_test --batch-test
./utility_copy_or_move_or_swap_test --batch-test
./utility_get_element_test --batch-test
./utility_get_test --batch-test
./utility_member_var_modify_helper_test --batch-test
./utility_pair_compare_test --batch-test
./utility_pair_get_test --batch-test
./utility_sao_buffer_test --batch-test
./utility_typeinfo_hasher_test --batch-test

source end_test_env_termux.sh
echo "---------all test end-----------------"
