#!/bin/sh
source ./begin_test_env_linux_x64.sh
rm -f Release-x64/gcc14/yggr_lua_base_type.so
rm -f Release-x64/gcc14/mongo_crypt_v1.so
ln -s libyggr_lua_base_type.so Release-x64/gcc14/yggr_lua_base_type.so
ln -s /usr/local/lib64/mongo_crypt/mongo_crypt_v1.so  Release-x64/gcc14/mongo_crypt_v1.so
cd ./test
rm -fr ../test_out
rm -f yggr_lua_base_type.so
rm -f mongo_crypt_v1.so
ln -s ../Release-x64/gcc14/libyggr_lua_base_type.so yggr_lua_base_type.so
ln -s /usr/local/lib64/mongo_crypt/mongo_crypt_v1.so mongo_crypt_v1.so
../Release-x64/gcc14/algorithm_boyer_moore_horspool_test --batch-test
../Release-x64/gcc14/algorithm_boyer_moore_test --batch-test
../Release-x64/gcc14/algorithm_is_permutation_test --batch-test
../Release-x64/gcc14/algorithm_knuth_morris_pratt_test --batch-test
../Release-x64/gcc14/algorithm_lexicographical_c_compare_test --batch-test
../Release-x64/gcc14/algorithm_random_shuffle_test --batch-test
../Release-x64/gcc14/any_val_any_bson_serialize_test --batch-test
../Release-x64/gcc14/any_val_any_network_serialize_test --batch-test
../Release-x64/gcc14/any_val_any_operator_mgr_basic_type_mix_test --batch-test
../Release-x64/gcc14/any_val_any_operator_mgr_performance_test --batch-test
../Release-x64/gcc14/any_val_any_xml_serialize_test --batch-test
../Release-x64/gcc14/any_val_boost_any_operator_mgr_basic_type_test --batch-test
../Release-x64/gcc14/any_val_params_bson_serialize_test --batch-test
../Release-x64/gcc14/any_val_params_network_serialize_test --batch-test
../Release-x64/gcc14/any_val_params_network_serialize_test_utf8_string_key --batch-test
../Release-x64/gcc14/any_val_params_test_of_boost_any --batch-test
../Release-x64/gcc14/any_val_params_test_of_yggr_any --batch-test
../Release-x64/gcc14/any_val_params_xml_serialize_test --batch-test
../Release-x64/gcc14/any_val_params_xml_serialize_test_utf8_string_key --batch-test
../Release-x64/gcc14/any_val_yggr_any_operator_mgr_basic_type_test --batch-test
../Release-x64/gcc14/any_val_yggr_any_test --batch-test
../Release-x64/gcc14/archive_archive_inner_keys_test --batch-test
../Release-x64/gcc14/base_char16_32_test --batch-test
../Release-x64/gcc14/base_cpp_version_test --batch-test
../Release-x64/gcc14/base_create_object_test --batch-test
../Release-x64/gcc14/base_random_test --batch-test
../Release-x64/gcc14/base_test_compare_using_less --batch-test
../Release-x64/gcc14/base_version_test --batch-test
../Release-x64/gcc14/bind_ex_bind_comparer_test --batch-test
../Release-x64/gcc14/bytes_byte_size_test --batch-test
../Release-x64/gcc14/bytes_tuple_byte_size_test --batch-test
../Release-x64/gcc14/caller_gen_callable_object_test --batch-test
../Release-x64/gcc14/caller_to_params_call_test --batch-test
../Release-x64/gcc14/charset_basic_string_adp_helper_test --batch-test
../Release-x64/gcc14/charset_charset_base_foo_test --batch-test
../Release-x64/gcc14/charset_charset_converter_test --batch-test
../Release-x64/gcc14/charset_const_strings_test --batch-test
../Release-x64/gcc14/charset_default_charset_name_test --batch-test
../Release-x64/gcc14/charset_empty_string_string_view_check --batch-test
../Release-x64/gcc14/charset_escape_codes_converter_test --batch-test
../Release-x64/gcc14/charset_hex_converter_test --batch-test
../Release-x64/gcc14/charset_isomeric_same_utf8_string_test --batch-test
../Release-x64/gcc14/charset_native_string_test --batch-test
../Release-x64/gcc14/charset_string_byte_size_test --batch-test
../Release-x64/gcc14/charset_string_converter_test --batch-test
../Release-x64/gcc14/charset_string_view_test --batch-test
../Release-x64/gcc14/charset_strings_binary_pak_serialize --batch-test
../Release-x64/gcc14/charset_strings_network_pak_serialize --batch-test
../Release-x64/gcc14/charset_strings_text_pak_serialize --batch-test
../Release-x64/gcc14/charset_strings_xml_pak_serialize --batch-test
../Release-x64/gcc14/charset_utf8_char_arithmetic_test --batch-test
../Release-x64/gcc14/charset_utf8_char_cast_conflict_test --batch-test
../Release-x64/gcc14/charset_utf8_char_isomeric_same_test --batch-test
../Release-x64/gcc14/charset_utf8_char_reference_test --batch-test
../Release-x64/gcc14/charset_utf8_char_serialization_test --batch-test
../Release-x64/gcc14/charset_utf8_char_test --batch-test
../Release-x64/gcc14/charset_utf8_char_view_test --batch-test
../Release-x64/gcc14/charset_utf8_foos_test --batch-test
../Release-x64/gcc14/charset_utf8_string_args_test --batch-test
../Release-x64/gcc14/charset_utf8_string_binary_pak_serialize --batch-test
../Release-x64/gcc14/charset_utf8_string_boyer_moore_horspool_test --batch-test
../Release-x64/gcc14/charset_utf8_string_boyer_moore_test --batch-test
../Release-x64/gcc14/charset_utf8_string_bson_pak_test --batch-test
../Release-x64/gcc14/charset_utf8_string_getter --batch-test
../Release-x64/gcc14/charset_utf8_ssource end_test_env.sheric_same_deque_test --batch-test
../Release-x64/gcc14/container_isomeric_same_list_test --batch-test
../Release-x64/gcc14/container_isomeric_same_map_test --batch-test
../Release-x64/gcc14/container_isomeric_same_multimap_test --batch-test
../Release-x64/gcc14/container_isomeric_same_multiset_test --batch-test
../Release-x64/gcc14/container_isomeric_same_options_deque_test --batch-test
../Release-x64/gcc14/container_isomeric_same_options_map_test --batch-test
../Release-x64/gcc14/container_isomeric_same_options_multimap_test --batch-test
../Release-x64/gcc14/container_isomeric_same_options_multiset_test --batch-test
../Release-x64/gcc14/container_isomeric_same_options_set_test --batch-test
../Release-x64/gcc14/container_isomeric_same_options_vector_test --batch-test
../Release-x64/gcc14/container_isomeric_same_set_test --batch-test
../Release-x64/gcc14/container_isomeric_same_vector_test --batch-test
../Release-x64/gcc14/container_list_test --batch-test
../Release-x64/gcc14/container_map_node_handler_test --batch-test
../Release-x64/gcc14/container_map_test --batch-test
../Release-x64/gcc14/container_multi_index_node_handler_test --batch-test
../Release-x64/gcc14/container_multimap_test --batch-test
../Release-x64/gcc14/container_multiset_test --batch-test
../Release-x64/gcc14/container_options_deque_test --batch-test
../Release-x64/gcc14/container_options_map_node_handler_test --batch-test
../Release-x64/gcc14/container_options_map_test --batch-test
../Release-x64/gcc14/container_options_multimap_test --batch-test
../Release-x64/gcc14/container_options_multiset_test --batch-test
../Release-x64/gcc14/container_options_set_node_handler_test --batch-test
../Release-x64/gcc14/container_options_set_test --batch-test
../Release-x64/gcc14/container_options_vector_test --batch-test
../Release-x64/gcc14/container_queue_test --batch-test
../Release-x64/gcc14/container_set_node_handler_test --batch-test
../Release-x64/gcc14/container_set_test --batch-test
../Release-x64/gcc14/container_stack_test --batch-test
../Release-x64/gcc14/container_umap_node_handler_test --batch-test
../Release-x64/gcc14/container_uset_node_handler_test --batch-test
../Release-x64/gcc14/container_vector_test --batch-test
../Release-x64/gcc14/container_ex_array_ex_test --batch-test
../Release-x64/gcc14/container_ex_array_t_maker_test --batch-test
../Release-x64/gcc14/container_ex_is_allocator_test --batch-test
../Release-x64/gcc14/container_ex_is_container_test --batch-test
../Release-x64/gcc14/container_ex_native_array_ref_test --batch-test
../Release-x64/gcc14/database_system_database_accesser_test --batch-test
../Release-x64/gcc14/database_system_database_accesser_test_of_pool --batch-test
../Release-x64/gcc14/database_system_database_async_mgr_test --batch-test
../Release-x64/gcc14/database_system_database_connection_pool_test --batch-test
../Release-x64/gcc14/database_system_database_connection_pool_test_mt --batch-test
../Release-x64/gcc14/database_system_database_connection_test --batch-test
../Release-x64/gcc14/database_system_database_connection_test_mt --batch-test
../Release-x64/gcc14/database_system_database_mgr_test --batch-test
../Release-x64/gcc14/database_system_test_database_accesser_excel --batch-test
../Release-x64/gcc14/database_system_test_database_accesser_excel_extern_file --batch-test
../Release-x64/gcc14/database_system_test_database_accesser_excel_extern_sheet --batch-test
../Release-x64/gcc14/encryption_tool_blowfish_tool_test --batch-test
../Release-x64/gcc14/encryption_tool_hmacsha1_tool_test --batch-test
../Release-x64/gcc14/encryption_tool_hmacsha256_tool_test --batch-test
../Release-x64/gcc14/encryption_tool_md5_tool_test --batch-test
../Release-x64/gcc14/encryption_tool_packet_cypher_tool_test --batch-test
../Release-x64/gcc14/encryption_tool_safe_pak_tool_test --batch-test
../Release-x64/gcc14/encryption_tool_sha1_tool_test --batch-test
../Release-x64/gcc14/encryption_tool_sha256_tool_test --batch-test
../Release-x64/gcc14/exception_bson_pak_test_of_error_code --batch-test
../Release-x64/gcc14/exception_exception_default_log_test --batch-test
../Release-x64/gcc14/exception_exception_mongodb_log_test --batch-test
../Release-x64/gcc14/exception_exception_sqldb_log_test --batch-test
../Release-x64/gcc14/exception_exception_test --batch-test
../Release-x64/gcc14/exception_exception_thread_file_log_test --batch-test
../Release-x64/gcc14/exception_link_string --batch-test
../Release-x64/gcc14/file_system_cross_test_boost_filesystem --batch-test
../Release-x64/gcc14/file_system_local_fsys_operator_test_part1 --batch-test
../Release-x64/gcc14/file_system_local_fsys_operator_test_part2 --batch-test
../Release-x64/gcc14/file_system_local_fsys_operator_test_part3 --batch-test
../Release-x64/gcc14/file_system_make_path_object_test --batch-test
../Release-x64/gcc14/file_system_path_check_test_part1 --batch-test
../Release-x64/gcc14/file_system_path_check_test_part2 --batch-test
../Release-x64/gcc14/file_system_path_check_test_part3 --batch-test
../Release-x64/gcc14/func_cast_to_functional_base_test --batch-test
../Release-x64/gcc14/func_foo_noexcept_op_test --batch-test
../Release-x64/gcc14/func_foo_t_info_test --batch-test
../Release-x64/gcc14/func_foo_t_maker_test --batch-test
../Release-x64/gcc14/func_functional_args_size_test --batch-test
../Release-x64/gcc14/func_is_functional_test --batch-test
../Release-x64/gcc14/fuzzy_filter_search_test_part1 --batch-test
../Release-x64/gcc14/fuzzy_filter_search_test_part2 --batch-test
../Release-x64/gcc14/fuzzy_filter_string_test_part1 --batch-test
../Release-x64/gcc14/fuzzy_filter_string_test_part2 --batch-test
../Release-x64/gcc14/fuzzy_fuzzy_search_test_part1 --batch-test
../Release-x64/gcc14/fuzzy_fuzzy_search_test_part2 --batch-test
../Release-x64/gcc14/fuzzy_fuzzy_string_test_part1 --batch-test
../Release-x64/gcc14/fuzzy_fuzzy_string_test_part2 --batch-test
../Release-x64/gcc14/geometry_bresenham_dx_test --batch-test
../Release-x64/gcc14/geometry_bresenham_test --batch-test
../Release-x64/gcc14/geometry_geo_bezier_curve_gui_test --batch-test
../Release-x64/gcc14/geometry_geo_bezier_curve_test --batch-test
../Release-x64/gcc14/geometry_geo_line_segment_test --batch-test
../Release-x64/gcc14/geometry_geo_line_test --batch-test
../Release-x64/gcc14/geometry_geo_polygon_test --batch-test
../Release-x64/gcc14/geometry_geo_rectangle_test --batch-test
../Release-x64/gcc14/geometry_org_bresenham_test --batch-test
../Release-x64/gcc14/handler_center_handler_center_test --batch-test
../Release-x64/gcc14/handler_center_handler_center_test_performance --batch-test
../Release-x64/gcc14/handler_center_handler_center_test_same_id_and_out --batch-test
../Release-x64/gcc14/handler_center_handler_center_test_u32_id --batch-test
../Release-x64/gcc14/ids_id_generator_test --batch-test
../Release-x64/gcc14/ids_idn_test --batch-test
../Release-x64/gcc14/ids_uuid_bson_serialize_test --batch-test
../Release-x64/gcc14/iterator_ex_advance_copy_test --batch-test
../Release-x64/gcc14/iterator_ex_is_const_iterator_test --batch-test
../Release-x64/gcc14/iterator_ex_is_reverse_iterator_test --batch-test
../Release-x64/gcc14/iterator_ex_iterator_category_check_test --batch-test
../Release-x64/gcc14/iterator_ex_iterator_to_reference_t_test --batch-test
../Release-x64/gcc14/iterator_ex_iterator_to_value_t_test --batch-test
../Release-x64/gcc14/iterator_ex_iterator_traits_ex_test --batch-test
../Release-x64/gcc14/log_log_file_accesser_test --batch-test
../Release-x64/gcc14/log_log_file_mgr_accesser_test --batch-test
../Release-x64/gcc14/log_log_file_mgr_accesser_test2 --batch-test
../Release-x64/gcc14/log_log_file_mgr_op_caller_test --batch-test
../Release-x64/gcc14/log_log_file_mgr_op_test --batch-test
../Release-x64/gcc14/log_log_file_mgr_test --batch-test
../Release-x64/gcc14/log_log_file_op_caller_test --batch-test
../Release-x64/gcc14/log_log_file_op_test --batch-test
../Release-x64/gcc14/log_log_file_test --batch-test
../Release-x64/gcc14/log_log_mongodb_accesser_test --batch-test
../Release-x64/gcc14/log_log_mongodb_op_caller_test --batch-test
../Release-x64/gcc14/log_log_mongodb_op_test --batch-test
../Release-x64/gcc14/log_log_sql_db_accesser_test --batch-test
../Release-x64/gcc14/log_log_sql_db_op_caller_test --batch-test
../Release-x64/gcc14/log_log_sql_db_op_test --batch-test
../Release-x64/gcc14/log_log_thread_file_test --batch-test
../Release-x64/gcc14/lua_lua_base_type_test_d32 --batch-test
../Release-x64/gcc14/lua_lua_base_type_test_d64 --batch-test
../Release-x64/gcc14/lua_lua_base_type_test_type_info --batch-test
../Release-x64/gcc14/lua_lua_debug_helper_test --batch-test
../Release-x64/gcc14/lua_lua_export_any_test --batch-test
../Release-x64/gcc14/lua_lua_export_inner_process_id --batch-test
../Release-x64/gcc14/lua_lua_export_pair_test --batch-test
../Release-x64/gcc14/lua_lua_export_params_test --batch-test
../Release-x64/gcc14/lua_lua_export_uuid_test --batch-test
../Release-x64/gcc14/lua_lua_script_mgr_performance_test --batch-test
../Release-x64/gcc14/lua_lua_script_mgr_test --batch-test
../Release-x64/gcc14/lua_lua_script_mgr_test2 --batch-test
../Release-x64/gcc14/lua_lua_script_mgr_test3 --batch-test
../Release-x64/gcc14/lua_lua_script_mgr_test_same_id_and_out --batch-test
../Release-x64/gcc14/lua_lua_script_test --batch-test
../Release-x64/gcc14/lua_lua_wrap_boost_size_test --batch-test
../Release-x64/gcc14/lua_luabind_exports_any_link_error_test --batch-test
../Release-x64/gcc14/lua_wrap_allcator_test --batch-test
../Release-x64/gcc14/lua_wrap_base_t_test --batch-test
../Release-x64/gcc14/lua_wrap_bidirectional_iterator_test --batch-test
../Release-x64/gcc14/lua_wrap_deque_test --batch-test
../Release-x64/gcc14/lua_wrap_list_test --batch-test
../Release-x64/gcc14/lua_wrap_pair_test --batch-test
../Release-x64/gcc14/lua_wrap_random_access_iterator_test_part1 --batch-test
../Release-x64/gcc14/lua_wrap_random_access_iterator_test_part2 --batch-test
../Release-x64/gcc14/lua_wrap_reverse_iterator_test --batch-test
../Release-x64/gcc14/lua_wrap_vector_test --batch-test
../Release-x64/gcc14/mapping_static_index_mapping_test --batch-test
../Release-x64/gcc14/mapping_unique_mapping_test --batch-test
../Release-x64/gcc14/math_arrangement_test --batch-test
../Release-x64/gcc14/math_combination_test --batch-test
../Release-x64/gcc14/math_division_ex_test --batch-test
../Release-x64/gcc14/math_elo_rating_test --batch-test
../Release-x64/gcc14/math_factorial_test --batch-test
../Release-x64/gcc14/math_fast_sqrt_check --batch-test
../Release-x64/gcc14/math_gcd_lcm_test --batch-test
../Release-x64/gcc14/math_math_some_test --batch-test
../Release-x64/gcc14/math_matrix_hash_test --batch-test
../Release-x64/gcc14/math_matrix_test --batch-test
../Release-x64/gcc14/math_modulus_test --batch-test
../Release-x64/gcc14/math_moving_average_test --batch-test
../Release-x64/gcc14/math_odd_even_number_test --batch-test
../Release-x64/gcc14/math_odds_test --batch-test
../Release-x64/gcc14/math_pascals_triangle_test --batch-test
../Release-x64/gcc14/math_sign_test --batch-test
../Release-x64/gcc14/math_vector2d_test --batch-test
../Release-x64/gcc14/math_vector3d_test --batch-test
../Release-x64/gcc14/math_vector_and_matrix_nvp_seriaztion_test --batch-test
../Release-x64/gcc14/math_vector_and_matrix_seriaztion_test --batch-test
../Release-x64/gcc14/math_vector_hash_test --batch-test
../Release-x64/gcc14/memory_ex_allocator_traits_test --batch-test
../Release-x64/gcc14/mplex_cast_to_container_test --batch-test
../Release-x64/gcc14/mplex_conv_to_tuple_test --batch-test
../Release-x64/gcc14/mplex_get_reference_if_in_test --batch-test
../Release-x64/gcc14/mplex_interger_log2_test --batch-test
../Release-x64/gcc14/mplex_limits_test --batch-test
../Release-x64/gcc14/mplex_pointer_int_test --batch-test
../Release-x64/gcc14/mplex_pointer_to_reference_t_test --batch-test
../Release-x64/gcc14/mplex_pointer_to_value_t_test --batch-test
../Release-x64/gcc14/mplex_ptr_val_operator_test --batch-test
../Release-x64/gcc14/mplex_reference_to_pointer_t_test --batch-test
../Release-x64/gcc14/mplex_reference_to_value_t_test --batch-test
../Release-x64/gcc14/mplex_strict_sizeof_test --batch-test
../Release-x64/gcc14/mplex_template_repaceor_test --batch-test
../Release-x64/gcc14/mplex_typename_caster_test --batch-test
../Release-x64/gcc14/mplex_typename_swapper_test --batch-test
../Release-x64/gcc14/network_asio_timer_test --batch-test
../Release-x64/gcc14/network_base_network_packet_test --batch-test
../Release-x64/gcc14/network_bl_end_test --batch-test
../Release-x64/gcc14/network_io_service_pool_test --batch-test
../Release-x64/gcc14/network_network_info_test --batch-test
../Release-x64/gcc14/network_network_packet_test --batch-test
../Release-x64/gcc14/nsql_database_system_base_bson_test --batch-test
../Release-x64/gcc14/nsql_database_system_bson_serialize_test --batch-test
../Release-x64/gcc14/nsql_database_system_c_bson_basic_demo --batch-test
../Release-x64/gcc14/nsql_database_system_c_bson_basic_test --batch-test
../Release-x64/gcc14/nsql_database_system_c_bson_binary_buffer_ref_operator_set_test_equal --batch-test
../Release-x64/gcc14/nsql_database_system_c_bson_binary_buffer_ref_operator_set_test_liner_only --batch-test
../Release-x64/gcc14/nsql_database_system_c_bson_binary_buffer_ref_operator_set_test_sizeof_greater --batch-test
../Release-x64/gcc14/nsql_database_system_c_bson_binary_buffer_ref_operator_set_test_sizeof_less --batch-test
../Release-x64/gcc14/nsql_database_system_c_bson_binary_buffer_ref_test --batch-test
../Release-x64/gcc14/nsql_database_system_c_bson_binary_buffer_test --batch-test
../Release-x64/gcc14/nsql_database_system_c_bson_code_test --batch-test
../Release-x64/gcc14/nsql_database_system_c_bson_code_w_scope_test --batch-test
../Release-x64/gcc14/nsql_database_system_c_bson_date_test --batch-test
../Release-x64/gcc14/nsql_database_system_c_bson_date_time_timeval_test --batch-test
../Release-x64/gcc14/nsql_database_system_c_bson_dbpointer_test --batch-test
../Release-x64/gcc14/nsql_database_system_c_bson_decimal128_test --batch-test
../Release-x64/gcc14/nsql_database_system_c_bson_error_test --batch-test
../Release-x64/gcc14/nsql_database_system_c_bson_oid_test --batch-test
../Release-x64/gcc14/nsql_database_system_c_bson_oid_test2 --batch-test
../Release-x64/gcc14/nsql_database_system_c_bson_regex_test --batch-test
../Release-x64/gcc14/nsql_database_system_c_bson_symbol_test --batch-test
../Release-x64/gcc14/nsql_database_system_c_bson_time_test --batch-test
../Release-x64/gcc14/nsql_database_system_c_bson_timestamp_test --batch-test
../Release-x64/gcc14/nsql_database_system_c_bson_timeval_test --batch-test
../Release-x64/gcc14/nsql_database_system_c_bson_value_test --batch-test
../Release-x64/gcc14/nsql_database_system_c_bson_value_test2 --batch-test
../Release-x64/gcc14/nsql_database_system_c_mongo_apm_callbacks_test --batch-test
../Release-x64/gcc14/nsql_database_system_c_mongo_auto_encryption_opts_test --batch-test
../Release-x64/gcc14/nsql_database_system_c_mongo_client_encryption_datakey_opts_test --batch-test
../Release-x64/gcc14/nsql_database_system_c_mongo_client_encryption_encrypt_opts_test --batch-test
../Release-x64/gcc14/nsql_database_system_c_mongo_client_encryption_encrypt_range_opts_test --batch-test
../Release-x64/gcc14/nsql_database_system_c_mongo_client_encryption_opts_test --batch-test
../Release-x64/gcc14/nsql_database_system_c_mongo_client_encryption_rewrap_many_datakey_result_test --batch-test
../Release-x64/gcc14/nsql_database_system_c_mongo_connection_init_test --batch-test
../Release-x64/gcc14/nsql_database_system_c_mongo_find_and_modify_opts_test --batch-test
../Release-x64/gcc14/nsql_database_system_c_mongo_gridfs_file_opt_test --batch-test
../Release-x64/gcc14/nsql_database_system_c_mongo_gridfs_file_test --batch-test
../Release-x64/gcc14/nsql_database_system_c_mongo_host_info_test --batch-test
../Release-x64/gcc14/nsql_database_system_c_mongo_index_model_test --batch-test
../Release-x64/gcc14/nsql_database_system_c_mongo_read_concern_test --batch-test
../Release-x64/gcc14/nsql_database_system_c_mongo_read_prefs_test --batch-test
../Release-x64/gcc14/nsql_database_system_c_mongo_server_api_test --batch-test
../Release-x64/gcc14/nsql_database_system_c_mongo_ssl_opt_test --batch-test
../Release-x64/gcc14/nsql_database_system_c_mongo_stream_test --batch-test
../Release-x64/gcc14/nsql_database_system_c_mongo_uri_test --batch-test
../Release-x64/gcc14/nsql_database_system_c_mongo_write_concern_test --batch-test
../Release-x64/gcc14/nsql_database_system_cert_file_win32_load_failed_test --batch-test
../Release-x64/gcc14/nsql_database_system_mongo_accesser_encryption_test_of_connect --batch-test
../Release-x64/gcc14/nsql_database_system_mongo_accesser_encryption_test_of_connect_pool --batch-test
../Release-x64/gcc14/nsql_database_system_mongo_accesser_test_of_connection --batch-test
../Release-x64/gcc14/nsql_database_system_mongo_accesser_test_of_connection_mt --batch-test
../Release-x64/gcc14/nsql_database_system_mongo_accesser_test_of_connection_pool --batch-test
../Release-x64/gcc14/nsql_database_system_mongo_accesser_test_of_connection_pool_mt --batch-test
../Release-x64/gcc14/nsql_database_system_mongo_accesser_test_of_connection_sharding --batch-test
../Release-x64/gcc14/nsql_database_system_mongo_gridfs_bucket_org_test --batch-test
../Release-x64/gcc14/nsql_database_system_mongo_gridfs_org_test --batch-test
../Release-x64/gcc14/nsql_database_system_mongo_operators_dollar_cmd_def_test --batch-test
../Release-x64/gcc14/nsql_database_system_mongoc_connection_pool_test --batch-test
../Release-x64/gcc14/nsql_database_system_mongodbc_basic_connect_test --batch-test
../Release-x64/gcc14/nsql_database_system_test_mongodb_async_mgr --batch-test
../Release-x64/gcc14/nsql_database_system_test_mongodb_mgr --batch-test
../Release-x64/gcc14/packet_binary_archive_test --batch-test
../Release-x64/gcc14/packet_binary_file_archive_test --batch-test
../Release-x64/gcc14/packet_binary_pak_archive_test --batch-test
../Release-x64/gcc14/packet_binary_pak_warchive_test --batch-test
../Release-x64/gcc14/packet_bson_cmd_pak_test_of_container_midx --batch-test
../Release-x64/gcc14/packet_bson_cmd_pak_test_of_container_part1 --batch-test
../Release-x64/gcc14/packet_bson_cmd_pak_test_of_container_part2 --batch-test
../Release-x64/gcc14/packet_bson_pak_test_of_class_and_base --batch-test
../Release-x64/gcc14/packet_bson_pak_test_of_container_part1_1 --batch-test
../Release-x64/gcc14/packet_bson_pak_test_of_container_part1_2 --batch-test
../Release-x64/gcc14/packet_bson_pak_test_of_container_part2_1 --batch-test
../Release-x64/gcc14/packet_bson_pak_test_of_container_part2_2 --batch-test
../Release-x64/gcc14/packet_bson_pak_test_of_container_part3 --batch-test
../Release-x64/gcc14/packet_bson_pak_test_of_container_part4 --batch-test
../Release-x64/gcc14/packet_bson_pak_test_of_tuple_container --batch-test
../Release-x64/gcc14/packet_bug_test_bson_pak_man --batch-test
../Release-x64/gcc14/packet_network_32_64_x_serialization_test --batch-test
../Release-x64/gcc14/packet_packet_info_key_test --batch-test
../Release-x64/gcc14/packet_packet_info_test --batch-test
../Release-x64/gcc14/packet_polymiorphism_serialization --batch-test
../Release-x64/gcc14/packet_serialize_file_test --batch-test
../Release-x64/gcc14/packet_shared_ptr_bson_serialization_test --batch-test
../Release-x64/gcc14/packet_shared_ptr_serialization_test --batch-test
../Release-x64/gcc14/packet_string_serialization_test_eins --batch-test
../Release-x64/gcc14/packet_string_serialization_test_zwei --batch-test
../Release-x64/gcc14/packet_test_archive_udp_wrap --batch-test
../Release-x64/gcc14/packet_test_archive_udp_wrap_and_collecter --batch-test
../Release-x64/gcc14/packet_test_archive_vector --batch-test
../Release-x64/gcc14/packet_test_bson_serialization_include --batch-test
../Release-x64/gcc14/packet_test_encrypt_archive --batch-test
../Release-x64/gcc14/packet_test_packet_info_caster --batch-test
../Release-x64/gcc14/packet_text_archive_test --batch-test
../Release-x64/gcc14/packet_text_pak_archive_test --batch-test
../Release-x64/gcc14/packet_text_pak_warchive_test --batch-test
../Release-x64/gcc14/packet_xml_pak_archive_test --batch-test
../Release-x64/gcc14/packet_xml_pak_test_of_container_midx --batch-test
../Release-x64/gcc14/packet_xml_pak_warchive_test --batch-test
../Release-x64/gcc14/ppex_foo_params_test --batch-test
../Release-x64/gcc14/ppex_has_member_check_test --batch-test
../Release-x64/gcc14/ppex_params_expand_test --batch-test
../Release-x64/gcc14/ppex_string_symbol_test --batch-test
../Release-x64/gcc14/ppex_va_args_test --batch-test
../Release-x64/gcc14/proxy_proxy_mode_test --batch-test
../Release-x64/gcc14/regex_get_string_vector --batch-test
../Release-x64/gcc14/regex_regex_parse_test_part1 --batch-test
../Release-x64/gcc14/regex_regex_parse_test_part2 --batch-test
../Release-x64/gcc14/regex_regex_parse_test_part3 --batch-test
../Release-x64/gcc14/regex_sting_view_rangex_test --batch-test
../Release-x64/gcc14/regex_textlow --batch-test
../Release-x64/gcc14/regex_textlow_dir --batch-test
../Release-x64/gcc14/regex_textlow_fname --batch-test
../Release-x64/gcc14/regex_utf8_regex_parse_test_part1 --batch-test
../Release-x64/gcc14/regex_utf8_regex_parse_test_part2 --batch-test
../Release-x64/gcc14/safe_container_boost_container_list_opt_impl_test --batch-test
../Release-x64/gcc14/safe_container_boost_container_map_opt_impl_test --batch-test
../Release-x64/gcc14/safe_container_boost_container_mmap_opt_impl_test --batch-test
../Release-x64/gcc14/safe_container_boost_container_mset_opt_impl_test --batch-test
../Release-x64/gcc14/safe_container_boost_container_set_opt_impl_test --batch-test
../Release-x64/gcc14/safe_container_boost_multi_index_ha_opt_test --batch-test
../Release-x64/gcc14/safe_container_boost_multi_index_hashed_index_ha_opt_test --batch-test
../Release-x64/gcc14/safe_container_boost_multi_index_ordered_index_a_opt_test --batch-test
../Release-x64/gcc14/safe_container_boost_multi_index_random_access_index_a_opt_test --batch-test
../Release-x64/gcc14/safe_container_boost_multi_index_ranked_index_a_opt_test --batch-test
../Release-x64/gcc14/safe_container_boost_multi_index_safe_mode_not_thread_safe_test --batch-test
../Release-x64/gcc14/safe_container_boost_multi_index_sequenced_index_a_opt_test --batch-test
../Release-x64/gcc14/safe_container_boost_size_test --batch-test
../Release-x64/gcc14/safe_container_boost_unordered_map_opt_ha_test --batch-test
../Release-x64/gcc14/safe_container_boost_unordered_multimap_ha_opt_test --batch-test
../Release-x64/gcc14/safe_container_boost_unordered_multiset_ha_opt_test --batch-test
../Release-x64/gcc14/safe_container_boost_unordered_set_ha_opt_test --batch-test
../Release-x64/gcc14/safe_container_isomeric_same_safe_deque_test --batch-test
../Release-x64/gcc14/safe_container_isomeric_same_safe_list_test --batch-test
../Release-x64/gcc14/safe_container_isomeric_same_safe_list_test_no_opt --batch-test
../Release-x64/gcc14/safe_container_isomeric_same_safe_map_test --batch-test
../Release-x64/gcc14/safe_container_isomeric_same_safe_map_test_no_opt --batch-test
../Release-x64/gcc14/safe_container_isomeric_same_safe_multi_index_container_base_test --batch-test
../Release-x64/gcc14/safe_container_isomeric_same_safe_multimap_test --batch-test
../Release-x64/gcc14/safe_container_isomeric_same_safe_multimap_test_no_opt --batch-test
../Release-x64/gcc14/safe_container_isomeric_same_safe_multiset_test --batch-test
../Release-x64/gcc14/safe_container_isomeric_same_safe_multiset_test_no_opt --batch-test
../Release-x64/gcc14/safe_container_isomeric_same_safe_options_deque_test --batch-test
../Release-x64/gcc14/safe_container_isomeric_same_safe_options_map_test --batch-test
../Release-x64/gcc14/safe_container_isomeric_same_safe_options_map_test_no_opt --batch-test
../Release-x64/gcc14/safe_container_isomeric_same_safe_options_multimap_test --batch-test
../Release-x64/gcc14/safe_container_isomeric_same_safe_options_multimap_test_no_opt --batch-test
../Release-x64/gcc14/safe_container_isomeric_same_safe_options_multiset_test --batch-test
../Release-x64/gcc14/safe_container_isomeric_same_safe_options_multiset_test_no_opt --batch-test
../Release-x64/gcc14/safe_container_isomeric_same_safe_options_set_test --batch-test
../Release-x64/gcc14/safe_container_isomeric_same_safe_options_set_test_no_opt --batch-test
../Release-x64/gcc14/safe_container_isomeric_same_safe_options_vector_test --batch-test
../Release-x64/gcc14/safe_container_isomeric_same_safe_set_test --batch-test
../Release-x64/gcc14/safe_container_isomeric_same_safe_set_test_no_opt --batch-test
../Release-x64/gcc14/safe_container_isomeric_same_safe_unordered_map_test --batch-test
../Release-x64/gcc14/safe_container_isomeric_same_safe_unordered_multimap_test --batch-test
../Release-x64/gcc14/safe_container_isomeric_same_safe_unordered_multiset_test --batch-test
../Release-x64/gcc14/safe_container_isomeric_same_safe_unordered_set_test --batch-test
../Release-x64/gcc14/safe_container_isomeric_same_safe_vector_test --batch-test
../Release-x64/gcc14/safe_container_safe_buffered_object_test --batch-test
../Release-x64/gcc14/safe_container_safe_deque_test --batch-test
../Release-x64/gcc14/safe_container_safe_hashed_map_queue_test --batch-test
../Release-x64/gcc14/safe_container_safe_list_performance_test --batch-test
../Release-x64/gcc14/safe_container_safe_list_test_part1_1 --batch-test
../Release-x64/gcc14/safe_container_safe_list_test_part1_2 --batch-test
../Release-x64/gcc14/safe_container_safe_list_test_part1_no_opt --batch-test
../Release-x64/gcc14/safe_container_safe_list_test_part2 --batch-test
../Release-x64/gcc14/safe_container_safe_list_test_part2_no_opt --batch-test
../Release-x64/gcc14/safe_container_safe_map_test_part1_1 --batch-test
../Release-x64/gcc14/safe_container_safe_map_test_part1_1_no_opt --batch-test
../Release-x64/gcc14/safe_container_safe_map_test_part1_2 --batch-test
../Release-x64/gcc14/safe_container_safe_map_test_part1_2_no_opt --batch-test
../Release-x64/gcc14/safe_container_safe_map_test_part2 --batch-test
../Release-x64/gcc14/safe_container_safe_map_test_part2_no_opt --batch-test
../Release-x64/gcc14/safe_container_safe_multi_index_container_base_test_part1 --batch-test
../Release-x64/gcc14/safe_container_safe_multi_index_container_base_test_part2 --batch-test
../Release-x64/gcc14/safe_container_safe_multi_index_container_thread_safe_test --batch-test
../Release-x64/gcc14/safe_container_safe_multi_index_container_using_handler_test --batch-test
../Release-x64/gcc14/safe_container_safe_multi_index_range_and_modify_test --batch-test
../Release-x64/gcc14/safe_container_safe_multimap_test --batch-test
../Release-x64/gcc14/safe_container_safe_multimap_test_no_opt --batch-test
../Release-x64/gcc14/safe_container_safe_multiset_performance_test --batch-test
../Release-x64/gcc14/safe_container_safe_multiset_test --batch-test
../Release-x64/gcc14/safe_container_safe_multiset_test_no_opt --batch-test
../Release-x64/gcc14/safe_container_safe_options_deque_test --batch-test
../Release-x64/gcc14/safe_container_safe_options_map_test --batch-test
../Release-x64/gcc14/safe_container_safe_options_map_test_no_opt --batch-test
../Release-x64/gcc14/safe_container_safe_options_multimap_test --batch-test
../Release-x64/gcc14/safe_container_safe_options_multimap_test_no_opt --batch-test
../Release-x64/gcc14/safe_container_safe_options_multiset_test --batch-test
../Release-x64/gcc14/safe_container_safe_options_multiset_test_no_opt --batch-test
../Release-x64/gcc14/safe_container_safe_options_set_test --batch-test
../Release-x64/gcc14/safe_container_safe_options_set_test_no_opt --batch-test
../Release-x64/gcc14/safe_container_safe_options_vector_test --batch-test
../Release-x64/gcc14/safe_container_safe_priority_queue_test --batch-test
../Release-x64/gcc14/safe_container_safe_queue_test --batch-test
../Release-x64/gcc14/safe_container_safe_set_performance_test --batch-test
../Release-x64/gcc14/safe_container_safe_set_test --batch-test
../Release-x64/gcc14/safe_container_safe_set_test_no_opt --batch-test
../Release-x64/gcc14/safe_container_safe_stack_test --batch-test
../Release-x64/gcc14/safe_container_safe_stack_test_no_opt --batch-test
../Release-x64/gcc14/safe_container_safe_unordered_map_opt_performance_test --batch-test
../Release-x64/gcc14/safe_container_safe_unordered_map_test --batch-test
../Release-x64/gcc14/safe_container_safe_unordered_multimap_opt_performance_test --batch-test
../Release-x64/gcc14/safe_container_safe_unordered_multimap_test --batch-test
../Release-x64/gcc14/safe_container_safe_unordered_multiset_opt_performance_test --batch-test
../Release-x64/gcc14/safe_container_safe_unordered_multiset_test --batch-test
../Release-x64/gcc14/safe_container_safe_unordered_set_opt_performance_test --batch-test
../Release-x64/gcc14/safe_container_safe_unordered_set_test --batch-test
../Release-x64/gcc14/safe_container_safe_vector_test --batch-test
../Release-x64/gcc14/safe_container_safe_wrap_test --batch-test
../Release-x64/gcc14/segment_mem_mapped_string_serialization_test --batch-test
../Release-x64/gcc14/segment_segment_container_construct_test --batch-test
../Release-x64/gcc14/segment_segment_container_construct_test2 --batch-test
../Release-x64/gcc14/segment_segment_container_test --batch-test
../Release-x64/gcc14/segment_segment_safe_deque_test --batch-test
../Release-x64/gcc14/segment_segment_safe_list_test_part1 --batch-test
../Release-x64/gcc14/segment_segment_safe_list_test_part1_no_opt --batch-test
../Release-x64/gcc14/segment_segment_safe_list_test_part2 --batch-test
../Release-x64/gcc14/segment_segment_safe_list_test_part2_no_opt --batch-test
../Release-x64/gcc14/segment_segment_safe_list_test_part3 --batch-test
../Release-x64/gcc14/segment_segment_safe_list_test_part3_no_opt --batch-test
../Release-x64/gcc14/segment_segment_safe_map_test_part1 --batch-test
../Release-x64/gcc14/segment_segment_safe_map_test_part2 --batch-test
../Release-x64/gcc14/segment_segment_safe_map_test_part3 --batch-test
../Release-x64/gcc14/segment_segment_safe_multi_index_container_base_test_part1 --batch-test
../Release-x64/gcc14/segment_segment_safe_multi_index_container_base_test_part2 --batch-test
../Release-x64/gcc14/segment_segment_safe_multi_index_container_base_test_part3 --batch-test
../Release-x64/gcc14/segment_segment_safe_multi_index_container_base_test_part4 --batch-test
../Release-x64/gcc14/segment_segment_safe_multi_index_container_base_test_part5 --batch-test
../Release-x64/gcc14/segment_segment_safe_multi_index_container_base_test_part6 --batch-test
../Release-x64/gcc14/segment_segment_safe_multimap_test --batch-test
../Release-x64/gcc14/segment_segment_safe_multiset_test --batch-test
../Release-x64/gcc14/segment_segment_safe_options_deque_test --batch-test
../Release-x64/gcc14/segment_segment_safe_options_map_test_part1 --batch-test
../Release-x64/gcc14/segment_segment_safe_options_map_test_part2 --batch-test
../Release-x64/gcc14/segment_segment_safe_options_map_test_part3 --batch-test
../Release-x64/gcc14/segment_segment_safe_options_multimap_test --batch-test
../Release-x64/gcc14/segment_segment_safe_options_multiset_test --batch-test
../Release-x64/gcc14/segment_segment_safe_options_set_test --batch-test
../Release-x64/gcc14/segment_segment_safe_options_vector_test --batch-test
../Release-x64/gcc14/segment_segment_safe_priority_queue_test --batch-test
../Release-x64/gcc14/segment_segment_safe_queue_test --batch-test
../Release-x64/gcc14/segment_segment_safe_set_test --batch-test
../Release-x64/gcc14/segment_segment_safe_set_test_no_opt --batch-test
../Release-x64/gcc14/segment_segment_safe_stack_test_part1 --batch-test
../Release-x64/gcc14/segment_segment_safe_stack_test_part2 --batch-test
../Release-x64/gcc14/segment_segment_safe_stack_test_part3 --batch-test
../Release-x64/gcc14/segment_segment_safe_unordered_map_test_part1 --batch-test
../Release-x64/gcc14/segment_segment_safe_unordered_map_test_part2 --batch-test
../Release-x64/gcc14/segment_segment_safe_unordered_multimap_test --batch-test
../Release-x64/gcc14/segment_segment_safe_unordered_multiset_test --batch-test
../Release-x64/gcc14/segment_segment_safe_unordered_set_test --batch-test
../Release-x64/gcc14/segment_segment_safe_vector_test --batch-test
../Release-x64/gcc14/segment_segment_utf8_char_test --batch-test
../Release-x64/gcc14/segment_segment_utf8_string_test_part1 --batch-test
../Release-x64/gcc14/segment_segment_utf8_string_test_part2 --batch-test
../Release-x64/gcc14/segment_segment_utf8_string_test_part3 --batch-test
../Release-x64/gcc14/seh_seh_bad_alloc_test --batch-test
../Release-x64/gcc14/seh_seh_stack_overflow_test --batch-test
../Release-x64/gcc14/seh_seh_test --batch-test
../Release-x64/gcc14/seh_win_process_foo_test --batch-test
../Release-x64/gcc14/serialization_polymiorphism_export_test --batch-test
../Release-x64/gcc14/smart_ptr_ex_eliminate_virtual --batch-test
../Release-x64/gcc14/smart_ptr_ex_interface_ptr_test --batch-test
../Release-x64/gcc14/smart_ptr_ex_make_shared_test --batch-test
../Release-x64/gcc14/struct_conv_params_and_packet_info_conv_test --batch-test
../Release-x64/gcc14/task_ceneter_network_packet_task_ceneter_test --batch-test
../Release-x64/gcc14/task_ceneter_task_ceneter_test --batch-test
../Release-x64/gcc14/time_inner_process_shared_timer_mgr_test --batch-test
../Release-x64/gcc14/time_runtime_performance_test_test --batch-test
../Release-x64/gcc14/time_time_basic_foo_test --batch-test
../Release-x64/gcc14/time_time_serialization_test --batch-test
../Release-x64/gcc14/time_time_test --batch-test
../Release-x64/gcc14/time_timer_mgr_seh_test --batch-test
../Release-x64/gcc14/time_timer_mgr_test --batch-test
../Release-x64/gcc14/time_timer_test --batch-test
../Release-x64/gcc14/tuple_tuple_comparer_test --batch-test
../Release-x64/gcc14/tuple_tuple_test --batch-test
../Release-x64/gcc14/tuple_yggr_tuple_in_boost_fusion_test --batch-test
../Release-x64/gcc14/type_traits_bits_bytes_to_types_test --batch-test
../Release-x64/gcc14/type_traits_has_functional_member_t_test --batch-test
../Release-x64/gcc14/type_traits_has_operator_function_test --batch-test
../Release-x64/gcc14/type_traits_has_operator_index_member_access_test --batch-test
../Release-x64/gcc14/type_traits_has_operator_pointer_member_access_test --batch-test
../Release-x64/gcc14/type_traits_is_callable_test --batch-test
../Release-x64/gcc14/type_traits_is_convertiable_size_t_test --batch-test
../Release-x64/gcc14/type_traits_is_convertiable_test --batch-test
../Release-x64/gcc14/type_traits_is_same_tpl_test --batch-test
../Release-x64/gcc14/type_traits_operator_result_test --batch-test
../Release-x64/gcc14/type_traits_pointer_checker_test --batch-test
../Release-x64/gcc14/type_traits_reference_checker_test --batch-test
../Release-x64/gcc14/typeof_deduce_result_test --batch-test
../Release-x64/gcc14/typeof_default_value_test --batch-test
../Release-x64/gcc14/utility_args_holder_test --batch-test
../Release-x64/gcc14/utility_array_get_test --batch-test
../Release-x64/gcc14/utility_bit_counter_test --batch-test
../Release-x64/gcc14/utility_copy_or_move_or_swap_test --batch-test
../Release-x64/gcc14/utility_get_element_test --batch-test
../Release-x64/gcc14/utility_get_test --batch-test
../Release-x64/gcc14/utility_member_var_modify_helper_test --batch-test
../Release-x64/gcc14/utility_pair_compare_test --batch-test
../Release-x64/gcc14/utility_pair_get_test --batch-test
../Release-x64/gcc14/utility_sao_buffer_test --batch-test
../Release-x64/gcc14/utility_typeinfo_hasher_test --batch-test
echo "---------all test end-----------------"
cd ..
source ./end_test_env.sh
