cd /d %~dp0/test
rm -fr ../test_out
cp -fr ../Debug-Win32/vc100/yggr_lua_base_type.dll ./
"../Debug-Win32/vc100/algorithm_boyer_moore_horspool_test.exe" --batch-test
"../Debug-Win32/vc100/algorithm_boyer_moore_test.exe" --batch-test
"../Debug-Win32/vc100/algorithm_is_permutation_test.exe" --batch-test
"../Debug-Win32/vc100/algorithm_knuth_morris_pratt_test.exe" --batch-test
"../Debug-Win32/vc100/algorithm_lexicographical_c_compare_test.exe" --batch-test
"../Debug-Win32/vc100/algorithm_random_shuffle_test.exe" --batch-test
"../Debug-Win32/vc100/any_val_any_bson_serialize_test.exe" --batch-test
"../Debug-Win32/vc100/any_val_any_network_serialize_test.exe" --batch-test
"../Debug-Win32/vc100/any_val_any_operator_mgr_basic_type_mix_test.exe" --batch-test
"../Debug-Win32/vc100/any_val_any_operator_mgr_performance_test.exe" --batch-test
"../Debug-Win32/vc100/any_val_any_xml_serialize_test.exe" --batch-test
"../Debug-Win32/vc100/any_val_boost_any_operator_mgr_basic_type_test.exe" --batch-test
"../Debug-Win32/vc100/any_val_params_bson_serialize_test.exe" --batch-test
"../Debug-Win32/vc100/any_val_params_network_serialize_test.exe" --batch-test
"../Debug-Win32/vc100/any_val_params_network_serialize_test_utf8_string_key.exe" --batch-test
"../Debug-Win32/vc100/any_val_params_test_of_boost_any.exe" --batch-test
"../Debug-Win32/vc100/any_val_params_test_of_yggr_any.exe" --batch-test
"../Debug-Win32/vc100/any_val_params_xml_serialize_test.exe" --batch-test
"../Debug-Win32/vc100/any_val_params_xml_serialize_test_utf8_string_key.exe" --batch-test
"../Debug-Win32/vc100/any_val_yggr_any_operator_mgr_basic_type_test.exe" --batch-test
"../Debug-Win32/vc100/any_val_yggr_any_test.exe" --batch-test
"../Debug-Win32/vc100/archive_archive_inner_keys_test.exe" --batch-test
"../Debug-Win32/vc100/base_char16_32_test.exe" --batch-test
"../Debug-Win32/vc100/base_cpp_version_test.exe" --batch-test
"../Debug-Win32/vc100/base_create_object_test.exe" --batch-test
"../Debug-Win32/vc100/base_random_test.exe" --batch-test
"../Debug-Win32/vc100/base_test_compare_using_less.exe" --batch-test
"../Debug-Win32/vc100/base_version_test.exe" --batch-test
"../Debug-Win32/vc100/bind_ex_bind_comparer_test.exe" --batch-test
"../Debug-Win32/vc100/bytes_byte_size_test.exe" --batch-test
"../Debug-Win32/vc100/bytes_tuple_byte_size_test.exe" --batch-test
"../Debug-Win32/vc100/caller_gen_callable_object_test.exe" --batch-test
"../Debug-Win32/vc100/caller_to_params_call_test.exe" --batch-test
"../Debug-Win32/vc100/charset_basic_string_adp_helper_test.exe" --batch-test
"../Debug-Win32/vc100/charset_charset_base_foo_test.exe" --batch-test
"../Debug-Win32/vc100/charset_charset_converter_test.exe" --batch-test
"../Debug-Win32/vc100/charset_const_strings_test.exe" --batch-test
"../Debug-Win32/vc100/charset_default_charset_name_test.exe" --batch-test
"../Debug-Win32/vc100/charset_empty_string_string_view_check.exe" --batch-test
"../Debug-Win32/vc100/charset_escape_codes_converter_test.exe" --batch-test
"../Debug-Win32/vc100/charset_hex_converter_test.exe" --batch-test
"../Debug-Win32/vc100/charset_isomeric_same_utf8_string_test.exe" --batch-test
"../Debug-Win32/vc100/charset_native_string_test.exe" --batch-test
"../Debug-Win32/vc100/charset_string_byte_size_test.exe" --batch-test
"../Debug-Win32/vc100/charset_string_converter_test.exe" --batch-test
"../Debug-Win32/vc100/charset_string_view_test.exe" --batch-test
"../Debug-Win32/vc100/charset_strings_binary_pak_serialize.exe" --batch-test
"../Debug-Win32/vc100/charset_strings_network_pak_serialize.exe" --batch-test
"../Debug-Win32/vc100/charset_strings_text_pak_serialize.exe" --batch-test
"../Debug-Win32/vc100/charset_strings_xml_pak_serialize.exe" --batch-test
"../Debug-Win32/vc100/charset_utf8_char_arithmetic_test.exe" --batch-test
"../Debug-Win32/vc100/charset_utf8_char_cast_conflict_test.exe" --batch-test
"../Debug-Win32/vc100/charset_utf8_char_isomeric_same_test.exe" --batch-test
"../Debug-Win32/vc100/charset_utf8_char_reference_test.exe" --batch-test
"../Debug-Win32/vc100/charset_utf8_char_serialization_test.exe" --batch-test
"../Debug-Win32/vc100/charset_utf8_char_test.exe" --batch-test
"../Debug-Win32/vc100/charset_utf8_char_view_test.exe" --batch-test
"../Debug-Win32/vc100/charset_utf8_foos_test.exe" --batch-test
"../Debug-Win32/vc100/charset_utf8_string_args_test.exe" --batch-test
"../Debug-Win32/vc100/charset_utf8_string_binary_pak_serialize.exe" --batch-test
"../Debug-Win32/vc100/charset_utf8_string_boyer_moore_horspool_test.exe" --batch-test
"../Debug-Win32/vc100/charset_utf8_string_boyer_moore_test.exe" --batch-test
"../Debug-Win32/vc100/charset_utf8_string_bson_pak_test.exe" --batch-test
"../Debug-Win32/vc100/charset_utf8_string_getter.exe" --batch-test
"../Debug-Win32/vc100/charset_utf8_string_isomeric_same_test.exe" --batch-test
"../Debug-Win32/vc100/charset_utf8_string_knuth_morris_pratt_test.exe" --batch-test
"../Debug-Win32/vc100/charset_utf8_string_serialization_test.exe" --batch-test
"../Debug-Win32/vc100/charset_utf8_string_test.exe" --batch-test
"../Debug-Win32/vc100/charset_utf8_string_test2.exe" --batch-test
"../Debug-Win32/vc100/charset_utf8_string_view_test.exe" --batch-test
"../Debug-Win32/vc100/charset_utf8_string_xml_pak_serialize.exe" --batch-test
"../Debug-Win32/vc100/compaction_tool_zip_lzma_test.exe" --batch-test
"../Debug-Win32/vc100/compiler_link_test_msvc_maroc.exe" --batch-test
"../Debug-Win32/vc100/container_cast_to_native_array_reference_test.exe" --batch-test
"../Debug-Win32/vc100/container_deque_test.exe" --batch-test
"../Debug-Win32/vc100/container_isomeric_same_deque_test.exe" --batch-test
"../Debug-Win32/vc100/container_isomeric_same_list_test.exe" --batch-test
"../Debug-Win32/vc100/container_isomeric_same_map_test.exe" --batch-test
"../Debug-Win32/vc100/container_isomeric_same_multimap_test.exe" --batch-test
"../Debug-Win32/vc100/container_isomeric_same_multiset_test.exe" --batch-test
"../Debug-Win32/vc100/container_isomeric_same_options_deque_test.exe" --batch-test
"../Debug-Win32/vc100/container_isomeric_same_options_map_test.exe" --batch-test
"../Debug-Win32/vc100/container_isomeric_same_options_multimap_test.exe" --batch-test
"../Debug-Win32/vc100/container_isomeric_same_options_multiset_test.exe" --batch-test
"../Debug-Win32/vc100/container_isomeric_same_options_set_test.exe" --batch-test
"../Debug-Win32/vc100/container_isomeric_same_options_vector_test.exe" --batch-test
"../Debug-Win32/vc100/container_isomeric_same_set_test.exe" --batch-test
"../Debug-Win32/vc100/container_isomeric_same_vector_test.exe" --batch-test
"../Debug-Win32/vc100/container_list_test.exe" --batch-test
"../Debug-Win32/vc100/container_map_node_handler_test.exe" --batch-test
"../Debug-Win32/vc100/container_map_test.exe" --batch-test
"../Debug-Win32/vc100/container_multi_index_node_handler_test.exe" --batch-test
"../Debug-Win32/vc100/container_multimap_test.exe" --batch-test
"../Debug-Win32/vc100/container_multiset_test.exe" --batch-test
"../Debug-Win32/vc100/container_options_deque_test.exe" --batch-test
"../Debug-Win32/vc100/container_options_map_node_handler_test.exe" --batch-test
"../Debug-Win32/vc100/container_options_map_test.exe" --batch-test
"../Debug-Win32/vc100/container_options_multimap_test.exe" --batch-test
"../Debug-Win32/vc100/container_options_multiset_test.exe" --batch-test
"../Debug-Win32/vc100/container_options_set_node_handler_test.exe" --batch-test
"../Debug-Win32/vc100/container_options_set_test.exe" --batch-test
"../Debug-Win32/vc100/container_options_vector_test.exe" --batch-test
"../Debug-Win32/vc100/container_queue_test.exe" --batch-test
"../Debug-Win32/vc100/container_set_node_handler_test.exe" --batch-test
"../Debug-Win32/vc100/container_set_test.exe" --batch-test
"../Debug-Win32/vc100/container_stack_test.exe" --batch-test
"../Debug-Win32/vc100/container_umap_node_handler_test.exe" --batch-test
"../Debug-Win32/vc100/container_uset_node_handler_test.exe" --batch-test
"../Debug-Win32/vc100/container_vector_test.exe" --batch-test
"../Debug-Win32/vc100/container_ex_array_ex_test.exe" --batch-test
"../Debug-Win32/vc100/container_ex_array_t_maker_test.exe" --batch-test
"../Debug-Win32/vc100/container_ex_is_allocator_test.exe" --batch-test
"../Debug-Win32/vc100/container_ex_is_container_test.exe" --batch-test
"../Debug-Win32/vc100/container_ex_native_array_ref_test.exe" --batch-test
"../Debug-Win32/vc100/database_system_database_accesser_test.exe" --batch-test
"../Debug-Win32/vc100/database_system_database_accesser_test_of_pool.exe" --batch-test
"../Debug-Win32/vc100/database_system_database_async_mgr_test.exe" --batch-test
"../Debug-Win32/vc100/database_system_database_connection_pool_test.exe" --batch-test
"../Debug-Win32/vc100/database_system_database_connection_pool_test_mt.exe" --batch-test
"../Debug-Win32/vc100/database_system_database_connection_test.exe" --batch-test
"../Debug-Win32/vc100/database_system_database_connection_test_mt.exe" --batch-test
"../Debug-Win32/vc100/database_system_database_mgr_test.exe" --batch-test
"../Debug-Win32/vc100/database_system_test_database_accesser_excel.exe" --batch-test
"../Debug-Win32/vc100/database_system_test_database_accesser_excel_extern_file.exe" --batch-test
"../Debug-Win32/vc100/database_system_test_database_accesser_excel_extern_sheet.exe" --batch-test
"../Debug-Win32/vc100/encryption_tool_blowfish_tool_test.exe" --batch-test
"../Debug-Win32/vc100/encryption_tool_hmacsha1_tool_test.exe" --batch-test
"../Debug-Win32/vc100/encryption_tool_hmacsha256_tool_test.exe" --batch-test
"../Debug-Win32/vc100/encryption_tool_md5_tool_test.exe" --batch-test
"../Debug-Win32/vc100/encryption_tool_packet_cypher_tool_test.exe" --batch-test
"../Debug-Win32/vc100/encryption_tool_safe_pak_tool_test.exe" --batch-test
"../Debug-Win32/vc100/encryption_tool_sha1_tool_test.exe" --batch-test
"../Debug-Win32/vc100/encryption_tool_sha256_tool_test.exe" --batch-test
"../Debug-Win32/vc100/exception_bson_pak_test_of_error_code.exe" --batch-test
"../Debug-Win32/vc100/exception_exception_default_log_test.exe" --batch-test
"../Debug-Win32/vc100/exception_exception_mongodb_log_test.exe" --batch-test
"../Debug-Win32/vc100/exception_exception_sqldb_log_test.exe" --batch-test
"../Debug-Win32/vc100/exception_exception_test.exe" --batch-test
"../Debug-Win32/vc100/exception_exception_thread_file_log_test.exe" --batch-test
"../Debug-Win32/vc100/exception_link_string.exe" --batch-test
"../Debug-Win32/vc100/file_system_cross_test_boost_filesystem.exe" --batch-test
"../Debug-Win32/vc100/file_system_local_fsys_operator_test_part1.exe" --batch-test
"../Debug-Win32/vc100/file_system_local_fsys_operator_test_part2.exe" --batch-test
"../Debug-Win32/vc100/file_system_local_fsys_operator_test_part3.exe" --batch-test
"../Debug-Win32/vc100/file_system_make_path_object_test.exe" --batch-test
"../Debug-Win32/vc100/file_system_path_check_test_part1.exe" --batch-test
"../Debug-Win32/vc100/file_system_path_check_test_part2.exe" --batch-test
"../Debug-Win32/vc100/file_system_path_check_test_part3.exe" --batch-test
"../Debug-Win32/vc100/func_cast_to_functional_base_test.exe" --batch-test
"../Debug-Win32/vc100/func_foo_noexcept_op_test.exe" --batch-test
"../Debug-Win32/vc100/func_foo_t_info_test.exe" --batch-test
"../Debug-Win32/vc100/func_foo_t_maker_test.exe" --batch-test
"../Debug-Win32/vc100/func_functional_args_size_test.exe" --batch-test
"../Debug-Win32/vc100/func_is_functional_test.exe" --batch-test
"../Debug-Win32/vc100/fuzzy_filter_search_test_part1.exe" --batch-test
"../Debug-Win32/vc100/fuzzy_filter_search_test_part2.exe" --batch-test
"../Debug-Win32/vc100/fuzzy_filter_string_test_part1.exe" --batch-test
"../Debug-Win32/vc100/fuzzy_filter_string_test_part2.exe" --batch-test
"../Debug-Win32/vc100/fuzzy_fuzzy_search_test_part1.exe" --batch-test
"../Debug-Win32/vc100/fuzzy_fuzzy_search_test_part2.exe" --batch-test
"../Debug-Win32/vc100/fuzzy_fuzzy_string_test_part1.exe" --batch-test
"../Debug-Win32/vc100/fuzzy_fuzzy_string_test_part2.exe" --batch-test
"../Debug-Win32/vc100/geometry_bresenham_dx_test.exe" --batch-test
"../Debug-Win32/vc100/geometry_bresenham_test.exe" --batch-test
"../Debug-Win32/vc100/geometry_geo_bezier_curve_gui_test.exe" --batch-test
"../Debug-Win32/vc100/geometry_geo_bezier_curve_test.exe" --batch-test
"../Debug-Win32/vc100/geometry_geo_line_segment_test.exe" --batch-test
"../Debug-Win32/vc100/geometry_geo_line_test.exe" --batch-test
"../Debug-Win32/vc100/geometry_geo_polygon_test.exe" --batch-test
"../Debug-Win32/vc100/geometry_geo_rectangle_test.exe" --batch-test
"../Debug-Win32/vc100/geometry_org_bresenham_test.exe" --batch-test
"../Debug-Win32/vc100/handler_center_handler_center_test.exe" --batch-test
"../Debug-Win32/vc100/handler_center_handler_center_test_performance.exe" --batch-test
"../Debug-Win32/vc100/handler_center_handler_center_test_same_id_and_out.exe" --batch-test
"../Debug-Win32/vc100/handler_center_handler_center_test_u32_id.exe" --batch-test
"../Debug-Win32/vc100/ids_id_generator_test.exe" --batch-test
"../Debug-Win32/vc100/ids_idn_test.exe" --batch-test
"../Debug-Win32/vc100/ids_uuid_bson_serialize_test.exe" --batch-test
"../Debug-Win32/vc100/iterator_ex_advance_copy_test.exe" --batch-test
"../Debug-Win32/vc100/iterator_ex_is_const_iterator_test.exe" --batch-test
"../Debug-Win32/vc100/iterator_ex_is_reverse_iterator_test.exe" --batch-test
"../Debug-Win32/vc100/iterator_ex_iterator_category_check_test.exe" --batch-test
"../Debug-Win32/vc100/iterator_ex_iterator_to_reference_t_test.exe" --batch-test
"../Debug-Win32/vc100/iterator_ex_iterator_to_value_t_test.exe" --batch-test
"../Debug-Win32/vc100/iterator_ex_iterator_traits_ex_test.exe" --batch-test
"../Debug-Win32/vc100/log_log_file_accesser_test.exe" --batch-test
"../Debug-Win32/vc100/log_log_file_mgr_accesser_test.exe" --batch-test
"../Debug-Win32/vc100/log_log_file_mgr_accesser_test2.exe" --batch-test
"../Debug-Win32/vc100/log_log_file_mgr_op_caller_test.exe" --batch-test
"../Debug-Win32/vc100/log_log_file_mgr_op_test.exe" --batch-test
"../Debug-Win32/vc100/log_log_file_mgr_test.exe" --batch-test
"../Debug-Win32/vc100/log_log_file_op_caller_test.exe" --batch-test
"../Debug-Win32/vc100/log_log_file_op_test.exe" --batch-test
"../Debug-Win32/vc100/log_log_file_test.exe" --batch-test
"../Debug-Win32/vc100/log_log_mongodb_accesser_test.exe" --batch-test
"../Debug-Win32/vc100/log_log_mongodb_op_caller_test.exe" --batch-test
"../Debug-Win32/vc100/log_log_mongodb_op_test.exe" --batch-test
"../Debug-Win32/vc100/log_log_sql_db_accesser_test.exe" --batch-test
"../Debug-Win32/vc100/log_log_sql_db_op_caller_test.exe" --batch-test
"../Debug-Win32/vc100/log_log_sql_db_op_test.exe" --batch-test
"../Debug-Win32/vc100/log_log_thread_file_test.exe" --batch-test
"../Debug-Win32/vc100/lua_lua_base_type_test_d32.exe" --batch-test
"../Debug-Win32/vc100/lua_lua_base_type_test_d64.exe" --batch-test
"../Debug-Win32/vc100/lua_lua_base_type_test_type_info.exe" --batch-test
"../Debug-Win32/vc100/lua_lua_debug_helper_test.exe" --batch-test
"../Debug-Win32/vc100/lua_lua_export_any_test.exe" --batch-test
"../Debug-Win32/vc100/lua_lua_export_inner_process_id.exe" --batch-test
"../Debug-Win32/vc100/lua_lua_export_pair_test.exe" --batch-test
"../Debug-Win32/vc100/lua_lua_export_params_test.exe" --batch-test
"../Debug-Win32/vc100/lua_lua_export_uuid_test.exe" --batch-test
"../Debug-Win32/vc100/lua_lua_script_mgr_performance_test.exe" --batch-test
"../Debug-Win32/vc100/lua_lua_script_mgr_test.exe" --batch-test
"../Debug-Win32/vc100/lua_lua_script_mgr_test2.exe" --batch-test
"../Debug-Win32/vc100/lua_lua_script_mgr_test3.exe" --batch-test
"../Debug-Win32/vc100/lua_lua_script_mgr_test_same_id_and_out.exe" --batch-test
"../Debug-Win32/vc100/lua_lua_script_test.exe" --batch-test
"../Debug-Win32/vc100/lua_lua_wrap_boost_size_test.exe" --batch-test
"../Debug-Win32/vc100/lua_luabind_exports_any_link_error_test.exe" --batch-test
"../Debug-Win32/vc100/lua_wrap_allcator_test.exe" --batch-test
"../Debug-Win32/vc100/lua_wrap_base_t_test.exe" --batch-test
"../Debug-Win32/vc100/lua_wrap_bidirectional_iterator_test.exe" --batch-test
"../Debug-Win32/vc100/lua_wrap_deque_test.exe" --batch-test
"../Debug-Win32/vc100/lua_wrap_list_test.exe" --batch-test
"../Debug-Win32/vc100/lua_wrap_pair_test.exe" --batch-test
"../Debug-Win32/vc100/lua_wrap_random_access_iterator_test_part1.exe" --batch-test
"../Debug-Win32/vc100/lua_wrap_random_access_iterator_test_part2.exe" --batch-test
"../Debug-Win32/vc100/lua_wrap_reverse_iterator_test.exe" --batch-test
"../Debug-Win32/vc100/lua_wrap_vector_test.exe" --batch-test
"../Debug-Win32/vc100/mapping_static_index_mapping_test.exe" --batch-test
"../Debug-Win32/vc100/mapping_unique_mapping_test.exe" --batch-test
"../Debug-Win32/vc100/math_arrangement_test.exe" --batch-test
"../Debug-Win32/vc100/math_combination_test.exe" --batch-test
"../Debug-Win32/vc100/math_division_ex_test.exe" --batch-test
"../Debug-Win32/vc100/math_elo_rating_test.exe" --batch-test
"../Debug-Win32/vc100/math_factorial_test.exe" --batch-test
"../Debug-Win32/vc100/math_fast_sqrt_check.exe" --batch-test
"../Debug-Win32/vc100/math_gcd_lcm_test.exe" --batch-test
"../Debug-Win32/vc100/math_math_some_test.exe" --batch-test
"../Debug-Win32/vc100/math_matrix_hash_test.exe" --batch-test
"../Debug-Win32/vc100/math_matrix_test.exe" --batch-test
"../Debug-Win32/vc100/math_modulus_test.exe" --batch-test
"../Debug-Win32/vc100/math_moving_average_test.exe" --batch-test
"../Debug-Win32/vc100/math_odd_even_number_test.exe" --batch-test
"../Debug-Win32/vc100/math_odds_test.exe" --batch-test
"../Debug-Win32/vc100/math_pascals_triangle_test.exe" --batch-test
"../Debug-Win32/vc100/math_sign_test.exe" --batch-test
"../Debug-Win32/vc100/math_vector2d_test.exe" --batch-test
"../Debug-Win32/vc100/math_vector3d_test.exe" --batch-test
"../Debug-Win32/vc100/math_vector_and_matrix_nvp_seriaztion_test.exe" --batch-test
"../Debug-Win32/vc100/math_vector_and_matrix_seriaztion_test.exe" --batch-test
"../Debug-Win32/vc100/math_vector_hash_test.exe" --batch-test
"../Debug-Win32/vc100/memory_ex_allocator_traits_test.exe" --batch-test
"../Debug-Win32/vc100/mplex_cast_to_container_test.exe" --batch-test
"../Debug-Win32/vc100/mplex_conv_to_tuple_test.exe" --batch-test
"../Debug-Win32/vc100/mplex_get_reference_if_in_test.exe" --batch-test
"../Debug-Win32/vc100/mplex_interger_log2_test.exe" --batch-test
"../Debug-Win32/vc100/mplex_limits_test.exe" --batch-test
"../Debug-Win32/vc100/mplex_pointer_int_test.exe" --batch-test
"../Debug-Win32/vc100/mplex_pointer_to_reference_t_test.exe" --batch-test
"../Debug-Win32/vc100/mplex_pointer_to_value_t_test.exe" --batch-test
"../Debug-Win32/vc100/mplex_ptr_val_operator_test.exe" --batch-test
"../Debug-Win32/vc100/mplex_reference_to_pointer_t_test.exe" --batch-test
"../Debug-Win32/vc100/mplex_reference_to_value_t_test.exe" --batch-test
"../Debug-Win32/vc100/mplex_strict_sizeof_test.exe" --batch-test
"../Debug-Win32/vc100/mplex_template_repaceor_test.exe" --batch-test
"../Debug-Win32/vc100/mplex_typename_caster_test.exe" --batch-test
"../Debug-Win32/vc100/mplex_typename_swapper_test.exe" --batch-test
"../Debug-Win32/vc100/network_asio_timer_test.exe" --batch-test
"../Debug-Win32/vc100/network_base_network_packet_test.exe" --batch-test
"../Debug-Win32/vc100/network_bl_end_test.exe" --batch-test
"../Debug-Win32/vc100/network_io_service_pool_test.exe" --batch-test
"../Debug-Win32/vc100/network_network_info_test.exe" --batch-test
"../Debug-Win32/vc100/network_network_packet_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_base_bson_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_bson_serialize_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_c_bson_basic_demo.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_c_bson_basic_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_c_bson_binary_buffer_ref_operator_set_test_equal.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_c_bson_binary_buffer_ref_operator_set_test_liner_only.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_c_bson_binary_buffer_ref_operator_set_test_sizeof_greater.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_c_bson_binary_buffer_ref_operator_set_test_sizeof_less.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_c_bson_binary_buffer_ref_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_c_bson_binary_buffer_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_c_bson_code_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_c_bson_code_w_scope_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_c_bson_date_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_c_bson_date_time_timeval_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_c_bson_dbpointer_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_c_bson_decimal128_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_c_bson_error_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_c_bson_oid_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_c_bson_oid_test2.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_c_bson_regex_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_c_bson_symbol_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_c_bson_time_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_c_bson_timestamp_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_c_bson_timeval_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_c_bson_value_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_c_bson_value_test2.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_c_mongo_apm_callbacks_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_c_mongo_auto_encryption_opts_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_c_mongo_client_encryption_datakey_opts_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_c_mongo_client_encryption_encrypt_opts_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_c_mongo_client_encryption_encrypt_range_opts_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_c_mongo_client_encryption_opts_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_c_mongo_client_encryption_rewrap_many_datakey_result_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_c_mongo_connection_init_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_c_mongo_find_and_modify_opts_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_c_mongo_gridfs_file_opt_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_c_mongo_gridfs_file_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_c_mongo_host_info_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_c_mongo_index_model_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_c_mongo_read_concern_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_c_mongo_read_prefs_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_c_mongo_server_api_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_c_mongo_ssl_opt_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_c_mongo_stream_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_c_mongo_uri_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_c_mongo_write_concern_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_cert_file_win32_load_failed_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_mongo_accesser_encryption_test_of_connect.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_mongo_accesser_encryption_test_of_connect_pool.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_mongo_accesser_test_of_connection.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_mongo_accesser_test_of_connection_mt.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_mongo_accesser_test_of_connection_pool.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_mongo_accesser_test_of_connection_pool_mt.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_mongo_accesser_test_of_connection_sharding.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_mongo_gridfs_bucket_org_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_mongo_gridfs_org_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_mongo_operators_dollar_cmd_def_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_mongoc_connection_pool_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_mongodbc_basic_connect_test.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_test_mongodb_async_mgr.exe" --batch-test
"../Debug-Win32/vc100/nsql_database_system_test_mongodb_mgr.exe" --batch-test
"../Debug-Win32/vc100/packet_binary_archive_test.exe" --batch-test
"../Debug-Win32/vc100/packet_binary_file_archive_test.exe" --batch-test
"../Debug-Win32/vc100/packet_binary_pak_archive_test.exe" --batch-test
"../Debug-Win32/vc100/packet_binary_pak_warchive_test.exe" --batch-test
"../Debug-Win32/vc100/packet_bson_cmd_pak_test_of_container_midx.exe" --batch-test
"../Debug-Win32/vc100/packet_bson_cmd_pak_test_of_container_part1.exe" --batch-test
"../Debug-Win32/vc100/packet_bson_cmd_pak_test_of_container_part2.exe" --batch-test
"../Debug-Win32/vc100/packet_bson_pak_test_of_class_and_base.exe" --batch-test
"../Debug-Win32/vc100/packet_bson_pak_test_of_container_part1_1.exe" --batch-test
"../Debug-Win32/vc100/packet_bson_pak_test_of_container_part1_2.exe" --batch-test
"../Debug-Win32/vc100/packet_bson_pak_test_of_container_part2_1.exe" --batch-test
"../Debug-Win32/vc100/packet_bson_pak_test_of_container_part2_2.exe" --batch-test
"../Debug-Win32/vc100/packet_bson_pak_test_of_container_part3.exe" --batch-test
"../Debug-Win32/vc100/packet_bson_pak_test_of_container_part4.exe" --batch-test
"../Debug-Win32/vc100/packet_bson_pak_test_of_tuple_container.exe" --batch-test
"../Debug-Win32/vc100/packet_bug_test_bson_pak_man.exe" --batch-test
"../Debug-Win32/vc100/packet_network_32_64_x_serialization_test.exe" --batch-test
"../Debug-Win32/vc100/packet_packet_info_key_test.exe" --batch-test
"../Debug-Win32/vc100/packet_packet_info_test.exe" --batch-test
"../Debug-Win32/vc100/packet_polymiorphism_serialization.exe" --batch-test
"../Debug-Win32/vc100/packet_serialize_file_test.exe" --batch-test
"../Debug-Win32/vc100/packet_shared_ptr_bson_serialization_test.exe" --batch-test
"../Debug-Win32/vc100/packet_shared_ptr_serialization_test.exe" --batch-test
"../Debug-Win32/vc100/packet_string_serialization_test_eins.exe" --batch-test
"../Debug-Win32/vc100/packet_string_serialization_test_zwei.exe" --batch-test
"../Debug-Win32/vc100/packet_test_archive_udp_wrap.exe" --batch-test
"../Debug-Win32/vc100/packet_test_archive_udp_wrap_and_collecter.exe" --batch-test
"../Debug-Win32/vc100/packet_test_archive_vector.exe" --batch-test
"../Debug-Win32/vc100/packet_test_bson_serialization_include.exe" --batch-test
"../Debug-Win32/vc100/packet_test_encrypt_archive.exe" --batch-test
"../Debug-Win32/vc100/packet_test_packet_info_caster.exe" --batch-test
"../Debug-Win32/vc100/packet_text_archive_test.exe" --batch-test
"../Debug-Win32/vc100/packet_text_pak_archive_test.exe" --batch-test
"../Debug-Win32/vc100/packet_text_pak_warchive_test.exe" --batch-test
"../Debug-Win32/vc100/packet_xml_pak_archive_test.exe" --batch-test
"../Debug-Win32/vc100/packet_xml_pak_test_of_container_midx.exe" --batch-test
"../Debug-Win32/vc100/packet_xml_pak_warchive_test.exe" --batch-test
"../Debug-Win32/vc100/ppex_foo_params_test.exe" --batch-test
"../Debug-Win32/vc100/ppex_has_member_check_test.exe" --batch-test
"../Debug-Win32/vc100/ppex_params_expand_test.exe" --batch-test
"../Debug-Win32/vc100/ppex_string_symbol_test.exe" --batch-test
"../Debug-Win32/vc100/ppex_va_args_test.exe" --batch-test
"../Debug-Win32/vc100/proxy_proxy_mode_test.exe" --batch-test
"../Debug-Win32/vc100/regex_get_string_vector.exe" --batch-test
"../Debug-Win32/vc100/regex_regex_parse_test_part1.exe" --batch-test
"../Debug-Win32/vc100/regex_regex_parse_test_part2.exe" --batch-test
"../Debug-Win32/vc100/regex_regex_parse_test_part3.exe" --batch-test
"../Debug-Win32/vc100/regex_sting_view_rangex_test.exe" --batch-test
"../Debug-Win32/vc100/regex_textlow.exe" --batch-test
"../Debug-Win32/vc100/regex_textlow_dir.exe" --batch-test
"../Debug-Win32/vc100/regex_textlow_fname.exe" --batch-test
"../Debug-Win32/vc100/regex_utf8_regex_parse_test_part1.exe" --batch-test
"../Debug-Win32/vc100/regex_utf8_regex_parse_test_part2.exe" --batch-test
"../Debug-Win32/vc100/safe_container_boost_container_list_opt_impl_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_boost_container_map_opt_impl_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_boost_container_mmap_opt_impl_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_boost_container_mset_opt_impl_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_boost_container_set_opt_impl_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_boost_multi_index_ha_opt_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_boost_multi_index_hashed_index_ha_opt_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_boost_multi_index_ordered_index_a_opt_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_boost_multi_index_random_access_index_a_opt_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_boost_multi_index_ranked_index_a_opt_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_boost_multi_index_safe_mode_not_thread_safe_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_boost_multi_index_sequenced_index_a_opt_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_boost_size_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_boost_unordered_map_opt_ha_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_boost_unordered_multimap_ha_opt_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_boost_unordered_multiset_ha_opt_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_boost_unordered_set_ha_opt_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_isomeric_same_safe_deque_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_isomeric_same_safe_list_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_isomeric_same_safe_list_test_no_opt.exe" --batch-test
"../Debug-Win32/vc100/safe_container_isomeric_same_safe_map_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_isomeric_same_safe_map_test_no_opt.exe" --batch-test
"../Debug-Win32/vc100/safe_container_isomeric_same_safe_multi_index_container_base_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_isomeric_same_safe_multimap_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_isomeric_same_safe_multimap_test_no_opt.exe" --batch-test
"../Debug-Win32/vc100/safe_container_isomeric_same_safe_multiset_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_isomeric_same_safe_multiset_test_no_opt.exe" --batch-test
"../Debug-Win32/vc100/safe_container_isomeric_same_safe_options_deque_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_isomeric_same_safe_options_map_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_isomeric_same_safe_options_map_test_no_opt.exe" --batch-test
"../Debug-Win32/vc100/safe_container_isomeric_same_safe_options_multimap_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_isomeric_same_safe_options_multimap_test_no_opt.exe" --batch-test
"../Debug-Win32/vc100/safe_container_isomeric_same_safe_options_multiset_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_isomeric_same_safe_options_multiset_test_no_opt.exe" --batch-test
"../Debug-Win32/vc100/safe_container_isomeric_same_safe_options_set_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_isomeric_same_safe_options_set_test_no_opt.exe" --batch-test
"../Debug-Win32/vc100/safe_container_isomeric_same_safe_options_vector_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_isomeric_same_safe_set_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_isomeric_same_safe_set_test_no_opt.exe" --batch-test
"../Debug-Win32/vc100/safe_container_isomeric_same_safe_unordered_map_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_isomeric_same_safe_unordered_multimap_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_isomeric_same_safe_unordered_multiset_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_isomeric_same_safe_unordered_set_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_isomeric_same_safe_vector_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_buffered_object_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_deque_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_hashed_map_queue_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_list_performance_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_list_test_part1_1.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_list_test_part1_2.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_list_test_part1_no_opt.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_list_test_part2.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_list_test_part2_no_opt.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_map_test_part1_1.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_map_test_part1_1_no_opt.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_map_test_part1_2.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_map_test_part1_2_no_opt.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_map_test_part2.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_map_test_part2_no_opt.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_multi_index_container_base_test_part1.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_multi_index_container_base_test_part2.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_multi_index_container_thread_safe_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_multi_index_container_using_handler_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_multi_index_range_and_modify_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_multimap_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_multimap_test_no_opt.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_multiset_performance_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_multiset_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_multiset_test_no_opt.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_options_deque_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_options_map_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_options_map_test_no_opt.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_options_multimap_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_options_multimap_test_no_opt.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_options_multiset_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_options_multiset_test_no_opt.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_options_set_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_options_set_test_no_opt.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_options_vector_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_priority_queue_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_queue_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_set_performance_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_set_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_set_test_no_opt.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_stack_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_stack_test_no_opt.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_unordered_map_opt_performance_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_unordered_map_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_unordered_multimap_opt_performance_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_unordered_multimap_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_unordered_multiset_opt_performance_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_unordered_multiset_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_unordered_set_opt_performance_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_unordered_set_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_vector_test.exe" --batch-test
"../Debug-Win32/vc100/safe_container_safe_wrap_test.exe" --batch-test
"../Debug-Win32/vc100/segment_mem_mapped_string_serialization_test.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_container_construct_test.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_container_construct_test2.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_container_test.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_safe_deque_test.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_safe_list_test_part1.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_safe_list_test_part1_no_opt.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_safe_list_test_part2.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_safe_list_test_part2_no_opt.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_safe_list_test_part3.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_safe_list_test_part3_no_opt.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_safe_map_test_part1.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_safe_map_test_part2.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_safe_map_test_part3.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_safe_multi_index_container_base_test_part1.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_safe_multi_index_container_base_test_part2.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_safe_multi_index_container_base_test_part3.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_safe_multi_index_container_base_test_part4.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_safe_multi_index_container_base_test_part5.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_safe_multi_index_container_base_test_part6.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_safe_multimap_test.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_safe_multiset_test.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_safe_options_deque_test.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_safe_options_map_test_part1.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_safe_options_map_test_part2.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_safe_options_map_test_part3.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_safe_options_multimap_test.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_safe_options_multiset_test.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_safe_options_set_test.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_safe_options_vector_test.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_safe_priority_queue_test.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_safe_queue_test.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_safe_set_test.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_safe_set_test_no_opt.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_safe_stack_test_part1.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_safe_stack_test_part2.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_safe_stack_test_part3.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_safe_unordered_map_test_part1.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_safe_unordered_map_test_part2.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_safe_unordered_multimap_test.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_safe_unordered_multiset_test.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_safe_unordered_set_test.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_safe_vector_test.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_utf8_char_test.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_utf8_string_test_part1.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_utf8_string_test_part2.exe" --batch-test
"../Debug-Win32/vc100/segment_segment_utf8_string_test_part3.exe" --batch-test
"../Debug-Win32/vc100/seh_seh_bad_alloc_test.exe" --batch-test
"../Debug-Win32/vc100/seh_seh_stack_overflow_test.exe" --batch-test
"../Debug-Win32/vc100/seh_seh_test.exe" --batch-test
"../Debug-Win32/vc100/seh_win_process_foo_test.exe" --batch-test
"../Debug-Win32/vc100/serialization_polymiorphism_export_test.exe" --batch-test
"../Debug-Win32/vc100/smart_ptr_ex_eliminate_virtual.exe" --batch-test
"../Debug-Win32/vc100/smart_ptr_ex_interface_ptr_test.exe" --batch-test
"../Debug-Win32/vc100/smart_ptr_ex_make_shared_test.exe" --batch-test
"../Debug-Win32/vc100/struct_conv_params_and_packet_info_conv_test.exe" --batch-test
"../Debug-Win32/vc100/task_ceneter_network_packet_task_ceneter_test.exe" --batch-test
"../Debug-Win32/vc100/task_ceneter_task_ceneter_test.exe" --batch-test
"../Debug-Win32/vc100/time_inner_process_shared_timer_mgr_test.exe" --batch-test
"../Debug-Win32/vc100/time_runtime_performance_test_test.exe" --batch-test
"../Debug-Win32/vc100/time_time_basic_foo_test.exe" --batch-test
"../Debug-Win32/vc100/time_time_serialization_test.exe" --batch-test
"../Debug-Win32/vc100/time_time_test.exe" --batch-test
"../Debug-Win32/vc100/time_timer_mgr_seh_test.exe" --batch-test
"../Debug-Win32/vc100/time_timer_mgr_test.exe" --batch-test
"../Debug-Win32/vc100/time_timer_test.exe" --batch-test
"../Debug-Win32/vc100/tuple_tuple_comparer_test.exe" --batch-test
"../Debug-Win32/vc100/tuple_tuple_test.exe" --batch-test
"../Debug-Win32/vc100/tuple_yggr_tuple_in_boost_fusion_test.exe" --batch-test
"../Debug-Win32/vc100/type_traits_bits_bytes_to_types_test.exe" --batch-test
"../Debug-Win32/vc100/type_traits_has_functional_member_t_test.exe" --batch-test
"../Debug-Win32/vc100/type_traits_has_operator_function_test.exe" --batch-test
"../Debug-Win32/vc100/type_traits_has_operator_index_member_access_test.exe" --batch-test
"../Debug-Win32/vc100/type_traits_has_operator_pointer_member_access_test.exe" --batch-test
"../Debug-Win32/vc100/type_traits_is_callable_test.exe" --batch-test
"../Debug-Win32/vc100/type_traits_is_convertiable_size_t_test.exe" --batch-test
"../Debug-Win32/vc100/type_traits_is_convertiable_test.exe" --batch-test
"../Debug-Win32/vc100/type_traits_is_same_tpl_test.exe" --batch-test
"../Debug-Win32/vc100/type_traits_operator_result_test.exe" --batch-test
"../Debug-Win32/vc100/type_traits_pointer_checker_test.exe" --batch-test
"../Debug-Win32/vc100/type_traits_reference_checker_test.exe" --batch-test
"../Debug-Win32/vc100/typeof_deduce_result_test.exe" --batch-test
"../Debug-Win32/vc100/typeof_default_value_test.exe" --batch-test
"../Debug-Win32/vc100/utility_args_holder_test.exe" --batch-test
"../Debug-Win32/vc100/utility_array_get_test.exe" --batch-test
"../Debug-Win32/vc100/utility_bit_counter_test.exe" --batch-test
"../Debug-Win32/vc100/utility_copy_or_move_or_swap_test.exe" --batch-test
"../Debug-Win32/vc100/utility_get_element_test.exe" --batch-test
"../Debug-Win32/vc100/utility_get_test.exe" --batch-test
"../Debug-Win32/vc100/utility_member_var_modify_helper_test.exe" --batch-test
"../Debug-Win32/vc100/utility_pair_compare_test.exe" --batch-test
"../Debug-Win32/vc100/utility_pair_get_test.exe" --batch-test
"../Debug-Win32/vc100/utility_sao_buffer_test.exe" --batch-test
"../Debug-Win32/vc100/utility_typeinfo_hasher_test.exe" --batch-test
echo '---------all test end-----------------'
cd ..