APP_STL := gnustl_static
APP_CPPFLAGS := -frtti -fexceptions \
				-DCC_ENABLE_CHIPMUNK_INTEGRATION=1 \
				-DYGGR_SYS_DEFAULT_STRING_CHARSET=\"utf-8\" \
				-DYGGR_AT_LINUX -DYGGR_SERIALIZE_SIZE32 \
				-DYGGR_USE_FAST_MATH
APP_PLATFORM := android-8
