#
#	lzma definitions.
#

APP_ABI := all
APP_STL := c++_static

include $(CLEAR_VARS)

ifeq ($(NDK_DEBUG), 1)
	APP_DEBUG := True
	APP_OPTIM := debug
else
	APP_DEBUG := False
	APP_OPTIM := release
endif

USRDEF_APP_COMPILER_VERSION := clang
USRDEF_APP_COMPILER_VERSION_TAG := -clang

USRDEF_APP_BOOST_VERSION := 1_82
USRDEF_APP_BOOST_VERSION_TAG := -1_82

USRDEF_APP_PYTHON_VERSION := 312

USRDEF_APP_C_INCLUDE := 

USRDEF_APP_CFLAGS := 
USRDEF_APP_CFLAGS_DEBUG := 
USRDEF_APP_CFLAGS_RELEASE := 

USRDEF_APP_CPPFLAGS := 
USRDEF_APP_CPPFLAGS_DEBUG := 
USRDEF_APP_CPPFLAGS_RELEASE := 

USRDEF_APP_LDFLAGS := 
USRDEF_APP_LDFLAGS_DEBUG := 
USRDEF_APP_LDFLAGS_RELEASE := 

APP_CPPFLAGS := -std=c++03
APP_PLATFORM := android-21
