// constexpt_cfg.hpp

/****************************************************************************
Copyright (c) 2010-2024 yggdrasil

author: xu yang

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
****************************************************************************/

#ifndef __YGGR_BASE_CONSTEXPR_CFG_HPP__
#define __YGGR_BASE_CONSTEXPR_CFG_HPP__

#ifndef __YGGR_YGGR_DEF_H__
#	error "please include <yggr/base/yggrdef.h> !!!";
#endif // __YGGR_YGGR_CONFIG_H__

#ifndef BOOST_CONFIG_HPP
#  include <boost/config.hpp>
#endif // BOOST_CONFIG_HPP

#include <yggr/base/yggr_cpp_ver_config.hpp>

#if (BOOST_VERSION < 105100) || defined(BOOST_NO_CONSTEXPR)
#	if !defined(YGGR_NO_CONSTEXPR)
#		define YGGR_NO_CONSTEXPR
#	endif // YGGR_NO_CXX11_CONSTEXPR

#	define YGGR_CONSTEXPR
#	define YGGR_CONSTEXPR_OR_INLINE inline
#	define YGGR_STATIC_CONSTEXPR_OR_INLINE_STATIC inline static
#	define YGGR_CONSTEXPR_OR_CONST const
#	define YGGR_CONSTEXPR_OR_STATIC static
#	define YGGR_CONSTEXPR_OR_STATIC_CONST static const

#else

#	if defined(BOOST_CONSTEXPR)

#		define YGGR_CONSTEXPR BOOST_CONSTEXPR
#		define YGGR_CONSTEXPR_OR_INLINE BOOST_CONSTEXPR
#		define YGGR_STATIC_CONSTEXPR_OR_INLINE_STATIC static BOOST_CONSTEXPR
#		if defined(BOOST_CONSTEXPR_OR_CONST)
#			define YGGR_CONSTEXPR_OR_CONST BOOST_CONSTEXPR_OR_CONST
#		else
#			define YGGR_CONSTEXPR_OR_CONST BOOST_CONSTEXPR
#		endif // BOOST_CONSTEXPR_OR_CONST
#		define YGGR_CONSTEXPR_OR_STATIC BOOST_CONSTEXPR
#		define YGGR_CONSTEXPR_OR_STATIC_CONST BOOST_CONSTEXPR

#	else

#		define YGGR_CONSTEXPR constexpr
#		define YGGR_CONSTEXPR_OR_INLINE constexpr
#		define YGGR_STATIC_CONSTEXPR_OR_INLINE_STATIC static constexpr
#		define YGGR_CONSTEXPR_OR_CONST constexpr
#		define YGGR_CONSTEXPR_OR_STATIC constexpr
#		define YGGR_CONSTEXPR_OR_STATIC_CONST constexpr

#endif //BOOST_CONSTEXPR

#endif // BOOST_NO_CXX11_CONSTEXPR

#if (YGGR_CPP_VER_23 <= YGGR_CPP_VERSION)
#	if defined(__cpp_lib_constexpr_dynamic_alloc) && !defined(__clang__) 
#		define YGGR_CXX23_CONSTEXPR YGGR_CONSTEXPR	
#		define YGGR_CXX23_CONSTEXPR_OR_INLINE YGGR_CONSTEXPR_OR_INLINE
#		define YGGR_CXX23_STATIC_CONSTEXPR_OR_INLINE_STATIC YGGR_STATIC_CONSTEXPR_OR_INLINE_STATIC
#		define YGGR_CXX23_CONSTEXPR_OR_CONST YGGR_CONSTEXPR_OR_CONST
#		define YGGR_CXX23_CONSTEXPR_OR_STATIC YGGR_CONSTEXPR_OR_STATIC
#		define YGGR_CXX23_CONSTEXPR_OR_STATIC_CONST YGGR_CONSTEXPR_OR_STATIC_CONST
#	else
#		define YGGR_CXX23_CONSTEXPR
#		define YGGR_CXX23_CONSTEXPR_OR_INLINE inline
#		define YGGR_CXX23_STATIC_CONSTEXPR_OR_INLINE_STATIC inline static
#		define YGGR_CXX23_CONSTEXPR_OR_CONST const
#		define YGGR_CXX23_CONSTEXPR_OR_STATIC static
#		define YGGR_CXX23_CONSTEXPR_OR_STATIC_CONST static const
#	endif // (__cpp_lib_constexpr_dynamic_alloc) && !defined(__clang__) 
#else
#	define YGGR_CXX23_CONSTEXPR
#	define YGGR_CXX23_CONSTEXPR_OR_INLINE inline
#	define YGGR_CXX23_STATIC_CONSTEXPR_OR_INLINE_STATIC inline static
#	define YGGR_CXX23_CONSTEXPR_OR_CONST const
#	define YGGR_CXX23_CONSTEXPR_OR_STATIC static
#	define YGGR_CXX23_CONSTEXPR_OR_STATIC_CONST static const
#endif // (YGGR_CPP_VER_23 <= YGGR_CPP_VERSION)

#if (YGGR_CPP_VER_20 <= YGGR_CPP_VERSION)
#	if defined(__cpp_lib_constexpr_dynamic_alloc) && !defined(__clang__) 
#		define YGGR_CXX20_CONSTEXPR YGGR_CONSTEXPR	
#		define YGGR_CXX20_CONSTEXPR_OR_INLINE YGGR_CONSTEXPR_OR_INLINE
#		define YGGR_CXX20_STATIC_CONSTEXPR_OR_INLINE_STATIC YGGR_STATIC_CONSTEXPR_OR_INLINE_STATIC
#		define YGGR_CXX20_CONSTEXPR_OR_CONST YGGR_CONSTEXPR_OR_CONST
#		define YGGR_CXX20_CONSTEXPR_OR_STATIC YGGR_CONSTEXPR_OR_STATIC
#		define YGGR_CXX20_CONSTEXPR_OR_STATIC_CONST YGGR_CONSTEXPR_OR_STATIC_CONST
#	else
#		define YGGR_CXX20_CONSTEXPR
#		define YGGR_CXX20_CONSTEXPR_OR_INLINE inline
#		define YGGR_CXX20_STATIC_CONSTEXPR_OR_INLINE_STATIC inline static
#		define YGGR_CXX20_CONSTEXPR_OR_CONST const
#		define YGGR_CXX20_CONSTEXPR_OR_STATIC static
#		define YGGR_CXX20_CONSTEXPR_OR_STATIC_CONST static const
#	endif // (__cpp_lib_constexpr_dynamic_alloc) && !defined(__clang__) 
#else
#	define YGGR_CXX20_CONSTEXPR
#	define YGGR_CXX20_CONSTEXPR_OR_INLINE inline
#	define YGGR_CXX120_STATIC_CONSTEXPR_OR_INLINE_STATIC inline static
#	define YGGR_CXX20_CONSTEXPR_OR_CONST const
#	define YGGR_CXX20_CONSTEXPR_OR_STATIC static
#	define YGGR_CXX20_CONSTEXPR_OR_STATIC_CONST static const
#endif // (YGGR_CPP_VER_20 <= YGGR_CPP_VERSION)

#if (YGGR_CPP_VER_17 <= YGGR_CPP_VERSION)
#	define YGGR_CXX17_CONSTEXPR YGGR_CONSTEXPR	
#	define YGGR_CXX17_CONSTEXPR_OR_INLINE YGGR_CONSTEXPR_OR_INLINE
#	define YGGR_CXX17_STATIC_CONSTEXPR_OR_INLINE_STATIC YGGR_STATIC_CONSTEXPR_OR_INLINE_STATIC
#	define YGGR_CXX17_CONSTEXPR_OR_CONST YGGR_CONSTEXPR_OR_CONST
#	define YGGR_CXX17_CONSTEXPR_OR_STATIC YGGR_CONSTEXPR_OR_STATIC
#	define YGGR_CXX17_CONSTEXPR_OR_STATIC_CONST YGGR_CONSTEXPR_OR_STATIC_CONST
#else
#	define YGGR_CXX17_CONSTEXPR
#	define YGGR_CXX17_CONSTEXPR_OR_INLINE inline
#	define YGGR_CXX17_STATIC_CONSTEXPR_OR_INLINE_STATIC inline static 
#	define YGGR_CXX17_CONSTEXPR_OR_CONST const
#	define YGGR_CXX17_CONSTEXPR_OR_STATIC static
#	define YGGR_CXX17_CONSTEXPR_OR_STATIC_CONST static const
#endif // (YGGR_CPP_VER_17 <= YGGR_CPP_VERSION)

#if (YGGR_CPP_VER_14 <= YGGR_CPP_VERSION)
#	define YGGR_CXX14_CONSTEXPR YGGR_CONSTEXPR	
#	define YGGR_CXX14_CONSTEXPR_OR_INLINE YGGR_CONSTEXPR_OR_INLINE
#	define YGGR_CXX14_STATIC_CONSTEXPR_OR_INLINE_STATIC YGGR_STATIC_CONSTEXPR_OR_INLINE_STATIC
#	define YGGR_CXX14_CONSTEXPR_OR_CONST YGGR_CONSTEXPR_OR_CONST
#	define YGGR_CXX14_CONSTEXPR_OR_STATIC YGGR_CONSTEXPR_OR_STATIC
#	define YGGR_CXX14_CONSTEXPR_OR_STATIC_CONST YGGR_CONSTEXPR_OR_STATIC_CONST
#else
#	define YGGR_CXX14_CONSTEXPR
#	define YGGR_CXX14_CONSTEXPR_OR_INLINE inline
#	define YGGR_CXX14_STATIC_CONSTEXPR_OR_INLINE_STATIC inline static
#	define YGGR_CXX14_CONSTEXPR_OR_CONST const
#	define YGGR_CXX14_CONSTEXPR_OR_STATIC static
#	define YGGR_CXX14_CONSTEXPR_OR_STATIC_CONST static const
#endif // (YGGR_CPP_VER_14 <= YGGR_CPP_VERSION)

#if (YGGR_CPP_VER_11 <= YGGR_CPP_VERSION)
#	define YGGR_CXX11_CONSTEXPR YGGR_CONSTEXPR	
#	define YGGR_CXX11_CONSTEXPR_OR_INLINE YGGR_CONSTEXPR_OR_INLINE
#	define YGGR_CXX11_STATIC_CONSTEXPR_OR_INLINE_STATIC YGGR_STATIC_CONSTEXPR_OR_INLINE_STATIC
#	define YGGR_CXX11_CONSTEXPR_OR_CONST YGGR_CONSTEXPR_OR_CONST
#	define YGGR_CXX11_CONSTEXPR_OR_STATIC YGGR_CONSTEXPR_OR_STATIC
#	define YGGR_CXX11_CONSTEXPR_OR_STATIC_CONST YGGR_CONSTEXPR_OR_STATIC_CONST
#else
#	define YGGR_CXX11_CONSTEXPR
#	define YGGR_CXX11_CONSTEXPR_OR_INLINE inline
#	define YGGR_CXX11_STATIC_CONSTEXPR_OR_INLINE_STATIC inline static
#	define YGGR_CXX11_CONSTEXPR_OR_CONST const
#	define YGGR_CXX11_CONSTEXPR_OR_STATIC static
#	define YGGR_CXX11_CONSTEXPR_OR_STATIC_CONST static const
#endif // (YGGR_CPP_VER_11 <= YGGR_CPP_VERSION)

#endif // __YGGR_BASE_CONSTEXPR_CFG_HPP__

