#ifdef  _MSC_VER

// kill spurious warnings
#pragma	warning(disable: 4786)
#pragma	warning(disable: 4503)  // Kill decorated names too long
#pragma	warning(disable: 4100)  // Kill unreferenced formal parameter
#pragma	warning(disable: 4511)  // Kill unable to create default copy constructor
#pragma	warning(disable: 4512)  // Kill unable to create default assingment operator
#pragma warning(disable: 4355)  // Kill 'this': used in base initializer list
#pragma warning(disable: 4715)  // Kill not all control paths return a value

#pragma warning(push, 1)  // exclude errors generated by the standard header files
#endif
